// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockTaskStore

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskStore is an autogenerated mock type for the TaskStore type
type MockTaskStore struct {
	mock.Mock
}

type MockTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStore) EXPECT() *MockTaskStore_Expecter {
	return &MockTaskStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, task
func (_m *MockTaskStore) Create(ctx context.Context, task *domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockTaskStore_Expecter) Create(ctx interface{}, task interface{}) *MockTaskStore_Create_Call {
	return &MockTaskStore_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskStore_Create_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockTaskStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Task))
	})
	return _c
}

func (_c *MockTaskStore_Create_Call) Return(_a0 error) *MockTaskStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_Create_Call) RunAndReturn(run func(context.Context, *domain.Task) error) *MockTaskStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskStore_Delete_Call {
	return &MockTaskStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskStore_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_Delete_Call) Return(_a0 error) *MockTaskStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) Get(ctx context.Context, id string) (*domain.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) Get(ctx interface{}, id interface{}) *MockTaskStore_Get_Call {
	return &MockTaskStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTaskStore_Get_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_Get_Call) Return(_a0 *domain.Task, _a1 error) *MockTaskStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Task, error)) *MockTaskStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtree provides a mock function with given fields: ctx, rootID
func (_m *MockTaskStore) GetSubtree(ctx context.Context, rootID string) ([]*domain.Task, error) {
	ret := _m.Called(ctx, rootID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtree")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Task, error)); ok {
		return rf(ctx, rootID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Task); ok {
		r0 = rf(ctx, rootID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rootID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_GetSubtree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtree'
type MockTaskStore_GetSubtree_Call struct {
	*mock.Call
}

// GetSubtree is a helper method to define mock.On call
//   - ctx context.Context
//   - rootID string
func (_e *MockTaskStore_Expecter) GetSubtree(ctx interface{}, rootID interface{}) *MockTaskStore_GetSubtree_Call {
	return &MockTaskStore_GetSubtree_Call{Call: _e.mock.On("GetSubtree", ctx, rootID)}
}

func (_c *MockTaskStore_GetSubtree_Call) Run(run func(ctx context.Context, rootID string)) *MockTaskStore_GetSubtree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_GetSubtree_Call) Return(_a0 []*domain.Task, _a1 error) *MockTaskStore_GetSubtree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_GetSubtree_Call) RunAndReturn(run func(context.Context, string) ([]*domain.Task, error)) *MockTaskStore_GetSubtree_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatus provides a mock function with given fields: ctx, status
func (_m *MockTaskStore) ListByStatus(ctx context.Context, status domain.TaskStatus) ([]*domain.Task, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatus")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) ([]*domain.Task, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) []*domain.Task); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TaskStatus) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatus'
type MockTaskStore_ListByStatus_Call struct {
	*mock.Call
}

// ListByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.TaskStatus
func (_e *MockTaskStore_Expecter) ListByStatus(ctx interface{}, status interface{}) *MockTaskStore_ListByStatus_Call {
	return &MockTaskStore_ListByStatus_Call{Call: _e.mock.On("ListByStatus", ctx, status)}
}

func (_c *MockTaskStore_ListByStatus_Call) Run(run func(ctx context.Context, status domain.TaskStatus)) *MockTaskStore_ListByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TaskStatus))
	})
	return _c
}

func (_c *MockTaskStore_ListByStatus_Call) Return(_a0 []*domain.Task, _a1 error) *MockTaskStore_ListByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListByStatus_Call) RunAndReturn(run func(context.Context, domain.TaskStatus) ([]*domain.Task, error)) *MockTaskStore_ListByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTeam provides a mock function with given fields: ctx, teamSlug
func (_m *MockTaskStore) ListByTeam(ctx context.Context, teamSlug string) ([]*domain.Task, error) {
	ret := _m.Called(ctx, teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeam")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Task, error)); ok {
		return rf(ctx, teamSlug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Task); ok {
		r0 = rf(ctx, teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeam'
type MockTaskStore_ListByTeam_Call struct {
	*mock.Call
}

// ListByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamSlug string
func (_e *MockTaskStore_Expecter) ListByTeam(ctx interface{}, teamSlug interface{}) *MockTaskStore_ListByTeam_Call {
	return &MockTaskStore_ListByTeam_Call{Call: _e.mock.On("ListByTeam", ctx, teamSlug)}
}

func (_c *MockTaskStore_ListByTeam_Call) Run(run func(ctx context.Context, teamSlug string)) *MockTaskStore_ListByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_ListByTeam_Call) Return(_a0 []*domain.Task, _a1 error) *MockTaskStore_ListByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListByTeam_Call) RunAndReturn(run func(context.Context, string) ([]*domain.Task, error)) *MockTaskStore_ListByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, task
func (_m *MockTaskStore) Update(ctx context.Context, task *domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockTaskStore_Expecter) Update(ctx interface{}, task interface{}) *MockTaskStore_Update_Call {
	return &MockTaskStore_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskStore_Update_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockTaskStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Task))
	})
	return _c
}

func (_c *MockTaskStore_Update_Call) Return(_a0 error) *MockTaskStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_Update_Call) RunAndReturn(run func(context.Context, *domain.Task) error) *MockTaskStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskStore creates a new instance of MockTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStore {
	mock := &MockTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
