// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockContainerRuntime

import (
	context "context"
	time "time"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockContainerRuntime is an autogenerated mock type for the ContainerRuntime type
type MockContainerRuntime struct {
	mock.Mock
}

type MockContainerRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainerRuntime) EXPECT() *MockContainerRuntime_Expecter {
	return &MockContainerRuntime_Expecter{mock: &_m.Mock}
}

// CreateContainer provides a mock function with given fields: ctx, config
func (_m *MockContainerRuntime) CreateContainer(ctx context.Context, config domain.ContainerConfig) (string, error) {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ContainerConfig) (string, error)); ok {
		return rf(ctx, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ContainerConfig) string); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ContainerConfig) error); ok {
		r1 = rf(ctx, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainerRuntime_CreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContainer'
type MockContainerRuntime_CreateContainer_Call struct {
	*mock.Call
}

// CreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - config domain.ContainerConfig
func (_e *MockContainerRuntime_Expecter) CreateContainer(ctx interface{}, config interface{}) *MockContainerRuntime_CreateContainer_Call {
	return &MockContainerRuntime_CreateContainer_Call{Call: _e.mock.On("CreateContainer", ctx, config)}
}

func (_c *MockContainerRuntime_CreateContainer_Call) Run(run func(ctx context.Context, config domain.ContainerConfig)) *MockContainerRuntime_CreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ContainerConfig))
	})
	return _c
}

func (_c *MockContainerRuntime_CreateContainer_Call) Return(_a0 string, _a1 error) *MockContainerRuntime_CreateContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainerRuntime_CreateContainer_Call) RunAndReturn(run func(context.Context, domain.ContainerConfig) (string, error)) *MockContainerRuntime_CreateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// InspectContainer provides a mock function with given fields: ctx, containerID
func (_m *MockContainerRuntime) InspectContainer(ctx context.Context, containerID string) (*domain.ContainerInfo, error) {
	ret := _m.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainer")
	}

	var r0 *domain.ContainerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ContainerInfo, error)); ok {
		return rf(ctx, containerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ContainerInfo); ok {
		r0 = rf(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ContainerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainerRuntime_InspectContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectContainer'
type MockContainerRuntime_InspectContainer_Call struct {
	*mock.Call
}

// InspectContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockContainerRuntime_Expecter) InspectContainer(ctx interface{}, containerID interface{}) *MockContainerRuntime_InspectContainer_Call {
	return &MockContainerRuntime_InspectContainer_Call{Call: _e.mock.On("InspectContainer", ctx, containerID)}
}

func (_c *MockContainerRuntime_InspectContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockContainerRuntime_InspectContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockContainerRuntime_InspectContainer_Call) Return(_a0 *domain.ContainerInfo, _a1 error) *MockContainerRuntime_InspectContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainerRuntime_InspectContainer_Call) RunAndReturn(run func(context.Context, string) (*domain.ContainerInfo, error)) *MockContainerRuntime_InspectContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function with given fields: ctx
func (_m *MockContainerRuntime) ListContainers(ctx context.Context) ([]domain.ContainerInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []domain.ContainerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ContainerInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ContainerInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContainerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainerRuntime_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockContainerRuntime_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerRuntime_Expecter) ListContainers(ctx interface{}) *MockContainerRuntime_ListContainers_Call {
	return &MockContainerRuntime_ListContainers_Call{Call: _e.mock.On("ListContainers", ctx)}
}

func (_c *MockContainerRuntime_ListContainers_Call) Run(run func(ctx context.Context)) *MockContainerRuntime_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContainerRuntime_ListContainers_Call) Return(_a0 []domain.ContainerInfo, _a1 error) *MockContainerRuntime_ListContainers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainerRuntime_ListContainers_Call) RunAndReturn(run func(context.Context) ([]domain.ContainerInfo, error)) *MockContainerRuntime_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function with given fields: ctx, containerID
func (_m *MockContainerRuntime) RemoveContainer(ctx context.Context, containerID string) error {
	ret := _m.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainerRuntime_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockContainerRuntime_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockContainerRuntime_Expecter) RemoveContainer(ctx interface{}, containerID interface{}) *MockContainerRuntime_RemoveContainer_Call {
	return &MockContainerRuntime_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", ctx, containerID)}
}

func (_c *MockContainerRuntime_RemoveContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockContainerRuntime_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockContainerRuntime_RemoveContainer_Call) Return(_a0 error) *MockContainerRuntime_RemoveContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainerRuntime_RemoveContainer_Call) RunAndReturn(run func(context.Context, string) error) *MockContainerRuntime_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function with given fields: ctx, containerID
func (_m *MockContainerRuntime) StartContainer(ctx context.Context, containerID string) error {
	ret := _m.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainerRuntime_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockContainerRuntime_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockContainerRuntime_Expecter) StartContainer(ctx interface{}, containerID interface{}) *MockContainerRuntime_StartContainer_Call {
	return &MockContainerRuntime_StartContainer_Call{Call: _e.mock.On("StartContainer", ctx, containerID)}
}

func (_c *MockContainerRuntime_StartContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockContainerRuntime_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockContainerRuntime_StartContainer_Call) Return(_a0 error) *MockContainerRuntime_StartContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainerRuntime_StartContainer_Call) RunAndReturn(run func(context.Context, string) error) *MockContainerRuntime_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function with given fields: ctx, containerID, timeout
func (_m *MockContainerRuntime) StopContainer(ctx context.Context, containerID string, timeout time.Duration) error {
	ret := _m.Called(ctx, containerID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, containerID, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainerRuntime_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockContainerRuntime_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - timeout time.Duration
func (_e *MockContainerRuntime_Expecter) StopContainer(ctx interface{}, containerID interface{}, timeout interface{}) *MockContainerRuntime_StopContainer_Call {
	return &MockContainerRuntime_StopContainer_Call{Call: _e.mock.On("StopContainer", ctx, containerID, timeout)}
}

func (_c *MockContainerRuntime_StopContainer_Call) Run(run func(ctx context.Context, containerID string, timeout time.Duration)) *MockContainerRuntime_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockContainerRuntime_StopContainer_Call) Return(_a0 error) *MockContainerRuntime_StopContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainerRuntime_StopContainer_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockContainerRuntime_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContainerRuntime creates a new instance of MockContainerRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerRuntime {
	mock := &MockContainerRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
