// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockLogStore

import (
	context "context"
	time "time"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockLogStore is an autogenerated mock type for the LogStore type
type MockLogStore struct {
	mock.Mock
}

type MockLogStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogStore) EXPECT() *MockLogStore_Expecter {
	return &MockLogStore_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockLogStore) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockLogStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLogStore_Expecter) Count(ctx interface{}) *MockLogStore_Count_Call {
	return &MockLogStore_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockLogStore_Count_Call) Run(run func(ctx context.Context)) *MockLogStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLogStore_Count_Call) Return(_a0 int64, _a1 error) *MockLogStore_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogStore_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockLogStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, entries
func (_m *MockLogStore) Create(ctx context.Context, entries []*domain.LogEntry) error {
	ret := _m.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.LogEntry) error); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLogStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []*domain.LogEntry
func (_e *MockLogStore_Expecter) Create(ctx interface{}, entries interface{}) *MockLogStore_Create_Call {
	return &MockLogStore_Create_Call{Call: _e.mock.On("Create", ctx, entries)}
}

func (_c *MockLogStore_Create_Call) Run(run func(ctx context.Context, entries []*domain.LogEntry)) *MockLogStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.LogEntry))
	})
	return _c
}

func (_c *MockLogStore_Create_Call) Return(_a0 error) *MockLogStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogStore_Create_Call) RunAndReturn(run func(context.Context, []*domain.LogEntry) error) *MockLogStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBefore provides a mock function with given fields: ctx, before
func (_m *MockLogStore) DeleteBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogStore_DeleteBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBefore'
type MockLogStore_DeleteBefore_Call struct {
	*mock.Call
}

// DeleteBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockLogStore_Expecter) DeleteBefore(ctx interface{}, before interface{}) *MockLogStore_DeleteBefore_Call {
	return &MockLogStore_DeleteBefore_Call{Call: _e.mock.On("DeleteBefore", ctx, before)}
}

func (_c *MockLogStore_DeleteBefore_Call) Run(run func(ctx context.Context, before time.Time)) *MockLogStore_DeleteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockLogStore_DeleteBefore_Call) Return(_a0 int64, _a1 error) *MockLogStore_DeleteBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogStore_DeleteBefore_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockLogStore_DeleteBefore_Call {
	_c.Call.Return(run)
	return _c
}

// GetOldest provides a mock function with given fields: ctx, limit
func (_m *MockLogStore) GetOldest(ctx context.Context, limit int) ([]*domain.LogEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetOldest")
	}

	var r0 []*domain.LogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.LogEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.LogEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogStore_GetOldest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOldest'
type MockLogStore_GetOldest_Call struct {
	*mock.Call
}

// GetOldest is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockLogStore_Expecter) GetOldest(ctx interface{}, limit interface{}) *MockLogStore_GetOldest_Call {
	return &MockLogStore_GetOldest_Call{Call: _e.mock.On("GetOldest", ctx, limit)}
}

func (_c *MockLogStore_GetOldest_Call) Run(run func(ctx context.Context, limit int)) *MockLogStore_GetOldest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockLogStore_GetOldest_Call) Return(_a0 []*domain.LogEntry, _a1 error) *MockLogStore_GetOldest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogStore_GetOldest_Call) RunAndReturn(run func(context.Context, int) ([]*domain.LogEntry, error)) *MockLogStore_GetOldest_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, opts
func (_m *MockLogStore) Query(ctx context.Context, opts domain.LogQueryOpts) ([]*domain.LogEntry, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*domain.LogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogQueryOpts) ([]*domain.LogEntry, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogQueryOpts) []*domain.LogEntry); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LogQueryOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogStore_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockLogStore_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.LogQueryOpts
func (_e *MockLogStore_Expecter) Query(ctx interface{}, opts interface{}) *MockLogStore_Query_Call {
	return &MockLogStore_Query_Call{Call: _e.mock.On("Query", ctx, opts)}
}

func (_c *MockLogStore_Query_Call) Run(run func(ctx context.Context, opts domain.LogQueryOpts)) *MockLogStore_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LogQueryOpts))
	})
	return _c
}

func (_c *MockLogStore_Query_Call) Return(_a0 []*domain.LogEntry, _a1 error) *MockLogStore_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogStore_Query_Call) RunAndReturn(run func(context.Context, domain.LogQueryOpts) ([]*domain.LogEntry, error)) *MockLogStore_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogStore creates a new instance of MockLogStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogStore {
	mock := &MockLogStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
