// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockSessionStore

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, chatJID
func (_m *MockSessionStore) Delete(ctx context.Context, chatJID string) error {
	ret := _m.Called(ctx, chatJID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, chatJID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - chatJID string
func (_e *MockSessionStore_Expecter) Delete(ctx interface{}, chatJID interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, chatJID)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(ctx context.Context, chatJID string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return(_a0 error) *MockSessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, chatJID
func (_m *MockSessionStore) Get(ctx context.Context, chatJID string) (*domain.ChatSession, error) {
	ret := _m.Called(ctx, chatJID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ChatSession, error)); ok {
		return rf(ctx, chatJID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ChatSession); ok {
		r0 = rf(ctx, chatJID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chatJID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - chatJID string
func (_e *MockSessionStore_Expecter) Get(ctx interface{}, chatJID interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, chatJID)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(ctx context.Context, chatJID string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(_a0 *domain.ChatSession, _a1 error) *MockSessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.ChatSession, error)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockSessionStore) ListAll(ctx context.Context) ([]*domain.ChatSession, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*domain.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.ChatSession, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.ChatSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockSessionStore_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionStore_Expecter) ListAll(ctx interface{}) *MockSessionStore_ListAll_Call {
	return &MockSessionStore_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockSessionStore_ListAll_Call) Run(run func(ctx context.Context)) *MockSessionStore_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionStore_ListAll_Call) Return(_a0 []*domain.ChatSession, _a1 error) *MockSessionStore_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_ListAll_Call) RunAndReturn(run func(context.Context) ([]*domain.ChatSession, error)) *MockSessionStore_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, session
func (_m *MockSessionStore) Upsert(ctx context.Context, session *domain.ChatSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ChatSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSessionStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.ChatSession
func (_e *MockSessionStore_Expecter) Upsert(ctx interface{}, session interface{}) *MockSessionStore_Upsert_Call {
	return &MockSessionStore_Upsert_Call{Call: _e.mock.On("Upsert", ctx, session)}
}

func (_c *MockSessionStore_Upsert_Call) Run(run func(ctx context.Context, session *domain.ChatSession)) *MockSessionStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ChatSession))
	})
	return _c
}

func (_c *MockSessionStore_Upsert_Call) Return(_a0 error) *MockSessionStore_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Upsert_Call) RunAndReturn(run func(context.Context, *domain.ChatSession) error) *MockSessionStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
