// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockTransactor

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function with given fields: fn
func (_m *MockTransactor) WithTransaction(fn func(*gorm.DB) error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*gorm.DB) error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockTransactor_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - fn func(*gorm.DB) error
func (_e *MockTransactor_Expecter) WithTransaction(fn interface{}) *MockTransactor_WithTransaction_Call {
	return &MockTransactor_WithTransaction_Call{Call: _e.mock.On("WithTransaction", fn)}
}

func (_c *MockTransactor_WithTransaction_Call) Run(run func(fn func(*gorm.DB) error)) *MockTransactor_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*gorm.DB) error))
	})
	return _c
}

func (_c *MockTransactor_WithTransaction_Call) Return(_a0 error) *MockTransactor_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_WithTransaction_Call) RunAndReturn(run func(func(*gorm.DB) error) error) *MockTransactor_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
