// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockMessageRouter

import (
	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageRouter is an autogenerated mock type for the MessageRouter type
type MockMessageRouter struct {
	mock.Mock
}

type MockMessageRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRouter) EXPECT() *MockMessageRouter_Expecter {
	return &MockMessageRouter_Expecter{mock: &_m.Mock}
}

// GetChannels provides a mock function with no fields
func (_m *MockMessageRouter) GetChannels() map[string]bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannels")
	}

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func() map[string]bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	return r0
}

// MockMessageRouter_GetChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannels'
type MockMessageRouter_GetChannels_Call struct {
	*mock.Call
}

// GetChannels is a helper method to define mock.On call
func (_e *MockMessageRouter_Expecter) GetChannels() *MockMessageRouter_GetChannels_Call {
	return &MockMessageRouter_GetChannels_Call{Call: _e.mock.On("GetChannels")}
}

func (_c *MockMessageRouter_GetChannels_Call) Run(run func()) *MockMessageRouter_GetChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageRouter_GetChannels_Call) Return(_a0 map[string]bool) *MockMessageRouter_GetChannels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRouter_GetChannels_Call) RunAndReturn(run func() map[string]bool) *MockMessageRouter_GetChannels_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterChannel provides a mock function with given fields: adapter
func (_m *MockMessageRouter) RegisterChannel(adapter domain.ChannelAdapter) error {
	ret := _m.Called(adapter)

	if len(ret) == 0 {
		panic("no return value specified for RegisterChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ChannelAdapter) error); ok {
		r0 = rf(adapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRouter_RegisterChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChannel'
type MockMessageRouter_RegisterChannel_Call struct {
	*mock.Call
}

// RegisterChannel is a helper method to define mock.On call
//   - adapter domain.ChannelAdapter
func (_e *MockMessageRouter_Expecter) RegisterChannel(adapter interface{}) *MockMessageRouter_RegisterChannel_Call {
	return &MockMessageRouter_RegisterChannel_Call{Call: _e.mock.On("RegisterChannel", adapter)}
}

func (_c *MockMessageRouter_RegisterChannel_Call) Run(run func(adapter domain.ChannelAdapter)) *MockMessageRouter_RegisterChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.ChannelAdapter))
	})
	return _c
}

func (_c *MockMessageRouter_RegisterChannel_Call) Return(_a0 error) *MockMessageRouter_RegisterChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRouter_RegisterChannel_Call) RunAndReturn(run func(domain.ChannelAdapter) error) *MockMessageRouter_RegisterChannel_Call {
	_c.Call.Return(run)
	return _c
}

// RouteInbound provides a mock function with given fields: jid, content
func (_m *MockMessageRouter) RouteInbound(jid string, content string) error {
	ret := _m.Called(jid, content)

	if len(ret) == 0 {
		panic("no return value specified for RouteInbound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(jid, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRouter_RouteInbound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RouteInbound'
type MockMessageRouter_RouteInbound_Call struct {
	*mock.Call
}

// RouteInbound is a helper method to define mock.On call
//   - jid string
//   - content string
func (_e *MockMessageRouter_Expecter) RouteInbound(jid interface{}, content interface{}) *MockMessageRouter_RouteInbound_Call {
	return &MockMessageRouter_RouteInbound_Call{Call: _e.mock.On("RouteInbound", jid, content)}
}

func (_c *MockMessageRouter_RouteInbound_Call) Run(run func(jid string, content string)) *MockMessageRouter_RouteInbound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockMessageRouter_RouteInbound_Call) Return(_a0 error) *MockMessageRouter_RouteInbound_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRouter_RouteInbound_Call) RunAndReturn(run func(string, string) error) *MockMessageRouter_RouteInbound_Call {
	_c.Call.Return(run)
	return _c
}

// RouteOutbound provides a mock function with given fields: jid, content
func (_m *MockMessageRouter) RouteOutbound(jid string, content string) error {
	ret := _m.Called(jid, content)

	if len(ret) == 0 {
		panic("no return value specified for RouteOutbound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(jid, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRouter_RouteOutbound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RouteOutbound'
type MockMessageRouter_RouteOutbound_Call struct {
	*mock.Call
}

// RouteOutbound is a helper method to define mock.On call
//   - jid string
//   - content string
func (_e *MockMessageRouter_Expecter) RouteOutbound(jid interface{}, content interface{}) *MockMessageRouter_RouteOutbound_Call {
	return &MockMessageRouter_RouteOutbound_Call{Call: _e.mock.On("RouteOutbound", jid, content)}
}

func (_c *MockMessageRouter_RouteOutbound_Call) Run(run func(jid string, content string)) *MockMessageRouter_RouteOutbound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockMessageRouter_RouteOutbound_Call) Return(_a0 error) *MockMessageRouter_RouteOutbound_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRouter_RouteOutbound_Call) RunAndReturn(run func(string, string) error) *MockMessageRouter_RouteOutbound_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterChannel provides a mock function with given fields: prefix
func (_m *MockMessageRouter) UnregisterChannel(prefix string) error {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRouter_UnregisterChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterChannel'
type MockMessageRouter_UnregisterChannel_Call struct {
	*mock.Call
}

// UnregisterChannel is a helper method to define mock.On call
//   - prefix string
func (_e *MockMessageRouter_Expecter) UnregisterChannel(prefix interface{}) *MockMessageRouter_UnregisterChannel_Call {
	return &MockMessageRouter_UnregisterChannel_Call{Call: _e.mock.On("UnregisterChannel", prefix)}
}

func (_c *MockMessageRouter_UnregisterChannel_Call) Run(run func(prefix string)) *MockMessageRouter_UnregisterChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMessageRouter_UnregisterChannel_Call) Return(_a0 error) *MockMessageRouter_UnregisterChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRouter_UnregisterChannel_Call) RunAndReturn(run func(string) error) *MockMessageRouter_UnregisterChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRouter creates a new instance of MockMessageRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRouter {
	mock := &MockMessageRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
