// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockMessageStore

import (
	context "context"
	time "time"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageStore is an autogenerated mock type for the MessageStore type
type MockMessageStore struct {
	mock.Mock
}

type MockMessageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageStore) EXPECT() *MockMessageStore_Expecter {
	return &MockMessageStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, msg
func (_m *MockMessageStore) Create(ctx context.Context, msg *domain.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.Message
func (_e *MockMessageStore_Expecter) Create(ctx interface{}, msg interface{}) *MockMessageStore_Create_Call {
	return &MockMessageStore_Create_Call{Call: _e.mock.On("Create", ctx, msg)}
}

func (_c *MockMessageStore_Create_Call) Run(run func(ctx context.Context, msg *domain.Message)) *MockMessageStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MockMessageStore_Create_Call) Return(_a0 error) *MockMessageStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageStore_Create_Call) RunAndReturn(run func(context.Context, *domain.Message) error) *MockMessageStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBefore provides a mock function with given fields: ctx, before
func (_m *MockMessageStore) DeleteBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStore_DeleteBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBefore'
type MockMessageStore_DeleteBefore_Call struct {
	*mock.Call
}

// DeleteBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockMessageStore_Expecter) DeleteBefore(ctx interface{}, before interface{}) *MockMessageStore_DeleteBefore_Call {
	return &MockMessageStore_DeleteBefore_Call{Call: _e.mock.On("DeleteBefore", ctx, before)}
}

func (_c *MockMessageStore_DeleteBefore_Call) Run(run func(ctx context.Context, before time.Time)) *MockMessageStore_DeleteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockMessageStore_DeleteBefore_Call) Return(_a0 int64, _a1 error) *MockMessageStore_DeleteBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStore_DeleteBefore_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockMessageStore_DeleteBefore_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByChat provides a mock function with given fields: ctx, chatJID
func (_m *MockMessageStore) DeleteByChat(ctx context.Context, chatJID string) error {
	ret := _m.Called(ctx, chatJID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, chatJID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageStore_DeleteByChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByChat'
type MockMessageStore_DeleteByChat_Call struct {
	*mock.Call
}

// DeleteByChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatJID string
func (_e *MockMessageStore_Expecter) DeleteByChat(ctx interface{}, chatJID interface{}) *MockMessageStore_DeleteByChat_Call {
	return &MockMessageStore_DeleteByChat_Call{Call: _e.mock.On("DeleteByChat", ctx, chatJID)}
}

func (_c *MockMessageStore_DeleteByChat_Call) Run(run func(ctx context.Context, chatJID string)) *MockMessageStore_DeleteByChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageStore_DeleteByChat_Call) Return(_a0 error) *MockMessageStore_DeleteByChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageStore_DeleteByChat_Call) RunAndReturn(run func(context.Context, string) error) *MockMessageStore_DeleteByChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChat provides a mock function with given fields: ctx, chatJID, since, limit
func (_m *MockMessageStore) GetByChat(ctx context.Context, chatJID string, since time.Time, limit int) ([]*domain.Message, error) {
	ret := _m.Called(ctx, chatJID, since, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByChat")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int) ([]*domain.Message, error)); ok {
		return rf(ctx, chatJID, since, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int) []*domain.Message); ok {
		r0 = rf(ctx, chatJID, since, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, int) error); ok {
		r1 = rf(ctx, chatJID, since, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStore_GetByChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChat'
type MockMessageStore_GetByChat_Call struct {
	*mock.Call
}

// GetByChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatJID string
//   - since time.Time
//   - limit int
func (_e *MockMessageStore_Expecter) GetByChat(ctx interface{}, chatJID interface{}, since interface{}, limit interface{}) *MockMessageStore_GetByChat_Call {
	return &MockMessageStore_GetByChat_Call{Call: _e.mock.On("GetByChat", ctx, chatJID, since, limit)}
}

func (_c *MockMessageStore_GetByChat_Call) Run(run func(ctx context.Context, chatJID string, since time.Time, limit int)) *MockMessageStore_GetByChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(int))
	})
	return _c
}

func (_c *MockMessageStore_GetByChat_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageStore_GetByChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStore_GetByChat_Call) RunAndReturn(run func(context.Context, string, time.Time, int) ([]*domain.Message, error)) *MockMessageStore_GetByChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatest provides a mock function with given fields: ctx, chatJID, n
func (_m *MockMessageStore) GetLatest(ctx context.Context, chatJID string, n int) ([]*domain.Message, error) {
	ret := _m.Called(ctx, chatJID, n)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*domain.Message, error)); ok {
		return rf(ctx, chatJID, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*domain.Message); ok {
		r0 = rf(ctx, chatJID, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, chatJID, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStore_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type MockMessageStore_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
//   - ctx context.Context
//   - chatJID string
//   - n int
func (_e *MockMessageStore_Expecter) GetLatest(ctx interface{}, chatJID interface{}, n interface{}) *MockMessageStore_GetLatest_Call {
	return &MockMessageStore_GetLatest_Call{Call: _e.mock.On("GetLatest", ctx, chatJID, n)}
}

func (_c *MockMessageStore_GetLatest_Call) Run(run func(ctx context.Context, chatJID string, n int)) *MockMessageStore_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockMessageStore_GetLatest_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageStore_GetLatest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStore_GetLatest_Call) RunAndReturn(run func(context.Context, string, int) ([]*domain.Message, error)) *MockMessageStore_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageStore creates a new instance of MockMessageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStore {
	mock := &MockMessageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
