// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockGoOrchestrator

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGoOrchestrator is an autogenerated mock type for the GoOrchestrator type
type MockGoOrchestrator struct {
	mock.Mock
}

type MockGoOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoOrchestrator) EXPECT() *MockGoOrchestrator_Expecter {
	return &MockGoOrchestrator_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function with given fields: ctx, taskID
func (_m *MockGoOrchestrator) CancelTask(ctx context.Context, taskID string) error {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type MockGoOrchestrator_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockGoOrchestrator_Expecter) CancelTask(ctx interface{}, taskID interface{}) *MockGoOrchestrator_CancelTask_Call {
	return &MockGoOrchestrator_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, taskID)}
}

func (_c *MockGoOrchestrator_CancelTask_Call) Run(run func(ctx context.Context, taskID string)) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_CancelTask_Call) Return(_a0 error) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_CancelTask_Call) RunAndReturn(run func(context.Context, string) error) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchTask provides a mock function with given fields: ctx, task
func (_m *MockGoOrchestrator) DispatchTask(ctx context.Context, task *domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for DispatchTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_DispatchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchTask'
type MockGoOrchestrator_DispatchTask_Call struct {
	*mock.Call
}

// DispatchTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockGoOrchestrator_Expecter) DispatchTask(ctx interface{}, task interface{}) *MockGoOrchestrator_DispatchTask_Call {
	return &MockGoOrchestrator_DispatchTask_Call{Call: _e.mock.On("DispatchTask", ctx, task)}
}

func (_c *MockGoOrchestrator_DispatchTask_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Task))
	})
	return _c
}

func (_c *MockGoOrchestrator_DispatchTask_Call) Return(_a0 error) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_DispatchTask_Call) RunAndReturn(run func(context.Context, *domain.Task) error) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTaskResult provides a mock function with given fields: result
func (_m *MockGoOrchestrator) HandleTaskResult(result *domain.TaskResult) error {
	ret := _m.Called(result)

	if len(ret) == 0 {
		panic("no return value specified for HandleTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.TaskResult) error); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_HandleTaskResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTaskResult'
type MockGoOrchestrator_HandleTaskResult_Call struct {
	*mock.Call
}

// HandleTaskResult is a helper method to define mock.On call
//   - result *domain.TaskResult
func (_e *MockGoOrchestrator_Expecter) HandleTaskResult(result interface{}) *MockGoOrchestrator_HandleTaskResult_Call {
	return &MockGoOrchestrator_HandleTaskResult_Call{Call: _e.mock.On("HandleTaskResult", result)}
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) Run(run func(result *domain.TaskResult)) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.TaskResult))
	})
	return _c
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) Return(_a0 error) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) RunAndReturn(run func(*domain.TaskResult) error) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Return(run)
	return _c
}

// RouteMessage provides a mock function with given fields: ctx, jid, content
func (_m *MockGoOrchestrator) RouteMessage(ctx context.Context, jid string, content string) error {
	ret := _m.Called(ctx, jid, content)

	if len(ret) == 0 {
		panic("no return value specified for RouteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, jid, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_RouteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RouteMessage'
type MockGoOrchestrator_RouteMessage_Call struct {
	*mock.Call
}

// RouteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - jid string
//   - content string
func (_e *MockGoOrchestrator_Expecter) RouteMessage(ctx interface{}, jid interface{}, content interface{}) *MockGoOrchestrator_RouteMessage_Call {
	return &MockGoOrchestrator_RouteMessage_Call{Call: _e.mock.On("RouteMessage", ctx, jid, content)}
}

func (_c *MockGoOrchestrator_RouteMessage_Call) Run(run func(ctx context.Context, jid string, content string)) *MockGoOrchestrator_RouteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_RouteMessage_Call) Return(_a0 error) *MockGoOrchestrator_RouteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_RouteMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGoOrchestrator_RouteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoOrchestrator creates a new instance of MockGoOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoOrchestrator {
	mock := &MockGoOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
