// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockGoOrchestrator

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGoOrchestrator is an autogenerated mock type for the GoOrchestrator type
type MockGoOrchestrator struct {
	mock.Mock
}

type MockGoOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoOrchestrator) EXPECT() *MockGoOrchestrator_Expecter {
	return &MockGoOrchestrator_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function with given fields: ctx, taskID
func (_m *MockGoOrchestrator) CancelTask(ctx context.Context, taskID string) error {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type MockGoOrchestrator_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockGoOrchestrator_Expecter) CancelTask(ctx interface{}, taskID interface{}) *MockGoOrchestrator_CancelTask_Call {
	return &MockGoOrchestrator_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, taskID)}
}

func (_c *MockGoOrchestrator_CancelTask_Call) Run(run func(ctx context.Context, taskID string)) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_CancelTask_Call) Return(_a0 error) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_CancelTask_Call) RunAndReturn(run func(context.Context, string) error) *MockGoOrchestrator_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubtasks provides a mock function with given fields: ctx, parentID, prompts, teamSlug
func (_m *MockGoOrchestrator) CreateSubtasks(ctx context.Context, parentID string, prompts []string, teamSlug string) ([]*domain.Task, error) {
	ret := _m.Called(ctx, parentID, prompts, teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubtasks")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]*domain.Task, error)); ok {
		return rf(ctx, parentID, prompts, teamSlug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) []*domain.Task); ok {
		r0 = rf(ctx, parentID, prompts, teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string) error); ok {
		r1 = rf(ctx, parentID, prompts, teamSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_CreateSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubtasks'
type MockGoOrchestrator_CreateSubtasks_Call struct {
	*mock.Call
}

// CreateSubtasks is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID string
//   - prompts []string
//   - teamSlug string
func (_e *MockGoOrchestrator_Expecter) CreateSubtasks(ctx interface{}, parentID interface{}, prompts interface{}, teamSlug interface{}) *MockGoOrchestrator_CreateSubtasks_Call {
	return &MockGoOrchestrator_CreateSubtasks_Call{Call: _e.mock.On("CreateSubtasks", ctx, parentID, prompts, teamSlug)}
}

func (_c *MockGoOrchestrator_CreateSubtasks_Call) Run(run func(ctx context.Context, parentID string, prompts []string, teamSlug string)) *MockGoOrchestrator_CreateSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_CreateSubtasks_Call) Return(_a0 []*domain.Task, _a1 error) *MockGoOrchestrator_CreateSubtasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_CreateSubtasks_Call) RunAndReturn(run func(context.Context, string, []string, string) ([]*domain.Task, error)) *MockGoOrchestrator_CreateSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, slug, leaderAID
func (_m *MockGoOrchestrator) CreateTeam(ctx context.Context, slug string, leaderAID string) (*domain.Team, error) {
	ret := _m.Called(ctx, slug, leaderAID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Team, error)); ok {
		return rf(ctx, slug, leaderAID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Team); ok {
		r0 = rf(ctx, slug, leaderAID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, slug, leaderAID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockGoOrchestrator_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - leaderAID string
func (_e *MockGoOrchestrator_Expecter) CreateTeam(ctx interface{}, slug interface{}, leaderAID interface{}) *MockGoOrchestrator_CreateTeam_Call {
	return &MockGoOrchestrator_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, slug, leaderAID)}
}

func (_c *MockGoOrchestrator_CreateTeam_Call) Run(run func(ctx context.Context, slug string, leaderAID string)) *MockGoOrchestrator_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_CreateTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockGoOrchestrator_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_CreateTeam_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Team, error)) *MockGoOrchestrator_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, slug
func (_m *MockGoOrchestrator) DeleteTeam(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockGoOrchestrator_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockGoOrchestrator_Expecter) DeleteTeam(ctx interface{}, slug interface{}) *MockGoOrchestrator_DeleteTeam_Call {
	return &MockGoOrchestrator_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, slug)}
}

func (_c *MockGoOrchestrator_DeleteTeam_Call) Run(run func(ctx context.Context, slug string)) *MockGoOrchestrator_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_DeleteTeam_Call) Return(_a0 error) *MockGoOrchestrator_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_DeleteTeam_Call) RunAndReturn(run func(context.Context, string) error) *MockGoOrchestrator_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchTask provides a mock function with given fields: ctx, task
func (_m *MockGoOrchestrator) DispatchTask(ctx context.Context, task *domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for DispatchTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_DispatchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchTask'
type MockGoOrchestrator_DispatchTask_Call struct {
	*mock.Call
}

// DispatchTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockGoOrchestrator_Expecter) DispatchTask(ctx interface{}, task interface{}) *MockGoOrchestrator_DispatchTask_Call {
	return &MockGoOrchestrator_DispatchTask_Call{Call: _e.mock.On("DispatchTask", ctx, task)}
}

func (_c *MockGoOrchestrator_DispatchTask_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Task))
	})
	return _c
}

func (_c *MockGoOrchestrator_DispatchTask_Call) Return(_a0 error) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_DispatchTask_Call) RunAndReturn(run func(context.Context, *domain.Task) error) *MockGoOrchestrator_DispatchTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllStatuses provides a mock function with no fields
func (_m *MockGoOrchestrator) GetAllStatuses() map[string]*domain.HeartbeatStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStatuses")
	}

	var r0 map[string]*domain.HeartbeatStatus
	if rf, ok := ret.Get(0).(func() map[string]*domain.HeartbeatStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.HeartbeatStatus)
		}
	}

	return r0
}

// MockGoOrchestrator_GetAllStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStatuses'
type MockGoOrchestrator_GetAllStatuses_Call struct {
	*mock.Call
}

// GetAllStatuses is a helper method to define mock.On call
func (_e *MockGoOrchestrator_Expecter) GetAllStatuses() *MockGoOrchestrator_GetAllStatuses_Call {
	return &MockGoOrchestrator_GetAllStatuses_Call{Call: _e.mock.On("GetAllStatuses")}
}

func (_c *MockGoOrchestrator_GetAllStatuses_Call) Run(run func()) *MockGoOrchestrator_GetAllStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoOrchestrator_GetAllStatuses_Call) Return(_a0 map[string]*domain.HeartbeatStatus) *MockGoOrchestrator_GetAllStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_GetAllStatuses_Call) RunAndReturn(run func() map[string]*domain.HeartbeatStatus) *MockGoOrchestrator_GetAllStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealthStatus provides a mock function with given fields: teamSlug
func (_m *MockGoOrchestrator) GetHealthStatus(teamSlug string) (*domain.HeartbeatStatus, error) {
	ret := _m.Called(teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthStatus")
	}

	var r0 *domain.HeartbeatStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.HeartbeatStatus, error)); ok {
		return rf(teamSlug)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.HeartbeatStatus); ok {
		r0 = rf(teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HeartbeatStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_GetHealthStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthStatus'
type MockGoOrchestrator_GetHealthStatus_Call struct {
	*mock.Call
}

// GetHealthStatus is a helper method to define mock.On call
//   - teamSlug string
func (_e *MockGoOrchestrator_Expecter) GetHealthStatus(teamSlug interface{}) *MockGoOrchestrator_GetHealthStatus_Call {
	return &MockGoOrchestrator_GetHealthStatus_Call{Call: _e.mock.On("GetHealthStatus", teamSlug)}
}

func (_c *MockGoOrchestrator_GetHealthStatus_Call) Run(run func(teamSlug string)) *MockGoOrchestrator_GetHealthStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_GetHealthStatus_Call) Return(_a0 *domain.HeartbeatStatus, _a1 error) *MockGoOrchestrator_GetHealthStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_GetHealthStatus_Call) RunAndReturn(run func(string) (*domain.HeartbeatStatus, error)) *MockGoOrchestrator_GetHealthStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskStatus provides a mock function with given fields: ctx, taskID
func (_m *MockGoOrchestrator) GetTaskStatus(ctx context.Context, taskID string) (*domain.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatus")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_GetTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskStatus'
type MockGoOrchestrator_GetTaskStatus_Call struct {
	*mock.Call
}

// GetTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockGoOrchestrator_Expecter) GetTaskStatus(ctx interface{}, taskID interface{}) *MockGoOrchestrator_GetTaskStatus_Call {
	return &MockGoOrchestrator_GetTaskStatus_Call{Call: _e.mock.On("GetTaskStatus", ctx, taskID)}
}

func (_c *MockGoOrchestrator_GetTaskStatus_Call) Run(run func(ctx context.Context, taskID string)) *MockGoOrchestrator_GetTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_GetTaskStatus_Call) Return(_a0 *domain.Task, _a1 error) *MockGoOrchestrator_GetTaskStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_GetTaskStatus_Call) RunAndReturn(run func(context.Context, string) (*domain.Task, error)) *MockGoOrchestrator_GetTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, slug
func (_m *MockGoOrchestrator) GetTeam(ctx context.Context, slug string) (*domain.Team, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockGoOrchestrator_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockGoOrchestrator_Expecter) GetTeam(ctx interface{}, slug interface{}) *MockGoOrchestrator_GetTeam_Call {
	return &MockGoOrchestrator_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, slug)}
}

func (_c *MockGoOrchestrator_GetTeam_Call) Run(run func(ctx context.Context, slug string)) *MockGoOrchestrator_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_GetTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockGoOrchestrator_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*domain.Team, error)) *MockGoOrchestrator_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTaskResult provides a mock function with given fields: ctx, taskID, result, errMsg
func (_m *MockGoOrchestrator) HandleTaskResult(ctx context.Context, taskID string, result string, errMsg string) error {
	ret := _m.Called(ctx, taskID, result, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for HandleTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, taskID, result, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_HandleTaskResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTaskResult'
type MockGoOrchestrator_HandleTaskResult_Call struct {
	*mock.Call
}

// HandleTaskResult is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - result string
//   - errMsg string
func (_e *MockGoOrchestrator_Expecter) HandleTaskResult(ctx interface{}, taskID interface{}, result interface{}, errMsg interface{}) *MockGoOrchestrator_HandleTaskResult_Call {
	return &MockGoOrchestrator_HandleTaskResult_Call{Call: _e.mock.On("HandleTaskResult", ctx, taskID, result, errMsg)}
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) Run(run func(ctx context.Context, taskID string, result string, errMsg string)) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) Return(_a0 error) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_HandleTaskResult_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockGoOrchestrator_HandleTaskResult_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUnhealthy provides a mock function with given fields: ctx, teamID
func (_m *MockGoOrchestrator) HandleUnhealthy(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for HandleUnhealthy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_HandleUnhealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUnhealthy'
type MockGoOrchestrator_HandleUnhealthy_Call struct {
	*mock.Call
}

// HandleUnhealthy is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockGoOrchestrator_Expecter) HandleUnhealthy(ctx interface{}, teamID interface{}) *MockGoOrchestrator_HandleUnhealthy_Call {
	return &MockGoOrchestrator_HandleUnhealthy_Call{Call: _e.mock.On("HandleUnhealthy", ctx, teamID)}
}

func (_c *MockGoOrchestrator_HandleUnhealthy_Call) Run(run func(ctx context.Context, teamID string)) *MockGoOrchestrator_HandleUnhealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoOrchestrator_HandleUnhealthy_Call) Return(_a0 error) *MockGoOrchestrator_HandleUnhealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_HandleUnhealthy_Call) RunAndReturn(run func(context.Context, string) error) *MockGoOrchestrator_HandleUnhealthy_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *MockGoOrchestrator) ListTeams(ctx context.Context) ([]*domain.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []*domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockGoOrchestrator_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoOrchestrator_Expecter) ListTeams(ctx interface{}) *MockGoOrchestrator_ListTeams_Call {
	return &MockGoOrchestrator_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *MockGoOrchestrator_ListTeams_Call) Run(run func(ctx context.Context)) *MockGoOrchestrator_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGoOrchestrator_ListTeams_Call) Return(_a0 []*domain.Team, _a1 error) *MockGoOrchestrator_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_ListTeams_Call) RunAndReturn(run func(context.Context) ([]*domain.Team, error)) *MockGoOrchestrator_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockGoOrchestrator) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockGoOrchestrator_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoOrchestrator_Expecter) Start(ctx interface{}) *MockGoOrchestrator_Start_Call {
	return &MockGoOrchestrator_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockGoOrchestrator_Start_Call) Run(run func(ctx context.Context)) *MockGoOrchestrator_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGoOrchestrator_Start_Call) Return(_a0 error) *MockGoOrchestrator_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_Start_Call) RunAndReturn(run func(context.Context) error) *MockGoOrchestrator_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockGoOrchestrator) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoOrchestrator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockGoOrchestrator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockGoOrchestrator_Expecter) Stop() *MockGoOrchestrator_Stop_Call {
	return &MockGoOrchestrator_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockGoOrchestrator_Stop_Call) Run(run func()) *MockGoOrchestrator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoOrchestrator_Stop_Call) Return(_a0 error) *MockGoOrchestrator_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoOrchestrator_Stop_Call) RunAndReturn(run func() error) *MockGoOrchestrator_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeam provides a mock function with given fields: ctx, slug, updates
func (_m *MockGoOrchestrator) UpdateTeam(ctx context.Context, slug string, updates map[string]interface{}) (*domain.Team, error) {
	ret := _m.Called(ctx, slug, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (*domain.Team, error)); ok {
		return rf(ctx, slug, updates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) *domain.Team); ok {
		r0 = rf(ctx, slug, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, slug, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoOrchestrator_UpdateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeam'
type MockGoOrchestrator_UpdateTeam_Call struct {
	*mock.Call
}

// UpdateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - updates map[string]interface{}
func (_e *MockGoOrchestrator_Expecter) UpdateTeam(ctx interface{}, slug interface{}, updates interface{}) *MockGoOrchestrator_UpdateTeam_Call {
	return &MockGoOrchestrator_UpdateTeam_Call{Call: _e.mock.On("UpdateTeam", ctx, slug, updates)}
}

func (_c *MockGoOrchestrator_UpdateTeam_Call) Run(run func(ctx context.Context, slug string, updates map[string]interface{})) *MockGoOrchestrator_UpdateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockGoOrchestrator_UpdateTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockGoOrchestrator_UpdateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoOrchestrator_UpdateTeam_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (*domain.Team, error)) *MockGoOrchestrator_UpdateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoOrchestrator creates a new instance of MockGoOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoOrchestrator {
	mock := &MockGoOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
