// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockTaskCoordinator

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskCoordinator is an autogenerated mock type for the TaskCoordinator type
type MockTaskCoordinator struct {
	mock.Mock
}

type MockTaskCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCoordinator) EXPECT() *MockTaskCoordinator_Expecter {
	return &MockTaskCoordinator_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function with given fields: ctx, taskID
func (_m *MockTaskCoordinator) CancelTask(ctx context.Context, taskID string) error {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCoordinator_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type MockTaskCoordinator_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskCoordinator_Expecter) CancelTask(ctx interface{}, taskID interface{}) *MockTaskCoordinator_CancelTask_Call {
	return &MockTaskCoordinator_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, taskID)}
}

func (_c *MockTaskCoordinator_CancelTask_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskCoordinator_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskCoordinator_CancelTask_Call) Return(_a0 error) *MockTaskCoordinator_CancelTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCoordinator_CancelTask_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskCoordinator_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubtasks provides a mock function with given fields: ctx, parentID, prompts, teamSlug
func (_m *MockTaskCoordinator) CreateSubtasks(ctx context.Context, parentID string, prompts []string, teamSlug string) ([]*domain.Task, error) {
	ret := _m.Called(ctx, parentID, prompts, teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubtasks")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]*domain.Task, error)); ok {
		return rf(ctx, parentID, prompts, teamSlug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) []*domain.Task); ok {
		r0 = rf(ctx, parentID, prompts, teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string) error); ok {
		r1 = rf(ctx, parentID, prompts, teamSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskCoordinator_CreateSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubtasks'
type MockTaskCoordinator_CreateSubtasks_Call struct {
	*mock.Call
}

// CreateSubtasks is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID string
//   - prompts []string
//   - teamSlug string
func (_e *MockTaskCoordinator_Expecter) CreateSubtasks(ctx interface{}, parentID interface{}, prompts interface{}, teamSlug interface{}) *MockTaskCoordinator_CreateSubtasks_Call {
	return &MockTaskCoordinator_CreateSubtasks_Call{Call: _e.mock.On("CreateSubtasks", ctx, parentID, prompts, teamSlug)}
}

func (_c *MockTaskCoordinator_CreateSubtasks_Call) Run(run func(ctx context.Context, parentID string, prompts []string, teamSlug string)) *MockTaskCoordinator_CreateSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(string))
	})
	return _c
}

func (_c *MockTaskCoordinator_CreateSubtasks_Call) Return(_a0 []*domain.Task, _a1 error) *MockTaskCoordinator_CreateSubtasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskCoordinator_CreateSubtasks_Call) RunAndReturn(run func(context.Context, string, []string, string) ([]*domain.Task, error)) *MockTaskCoordinator_CreateSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchTask provides a mock function with given fields: ctx, task
func (_m *MockTaskCoordinator) DispatchTask(ctx context.Context, task *domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for DispatchTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCoordinator_DispatchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchTask'
type MockTaskCoordinator_DispatchTask_Call struct {
	*mock.Call
}

// DispatchTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockTaskCoordinator_Expecter) DispatchTask(ctx interface{}, task interface{}) *MockTaskCoordinator_DispatchTask_Call {
	return &MockTaskCoordinator_DispatchTask_Call{Call: _e.mock.On("DispatchTask", ctx, task)}
}

func (_c *MockTaskCoordinator_DispatchTask_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockTaskCoordinator_DispatchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Task))
	})
	return _c
}

func (_c *MockTaskCoordinator_DispatchTask_Call) Return(_a0 error) *MockTaskCoordinator_DispatchTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCoordinator_DispatchTask_Call) RunAndReturn(run func(context.Context, *domain.Task) error) *MockTaskCoordinator_DispatchTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskStatus provides a mock function with given fields: ctx, taskID
func (_m *MockTaskCoordinator) GetTaskStatus(ctx context.Context, taskID string) (*domain.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatus")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskCoordinator_GetTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskStatus'
type MockTaskCoordinator_GetTaskStatus_Call struct {
	*mock.Call
}

// GetTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskCoordinator_Expecter) GetTaskStatus(ctx interface{}, taskID interface{}) *MockTaskCoordinator_GetTaskStatus_Call {
	return &MockTaskCoordinator_GetTaskStatus_Call{Call: _e.mock.On("GetTaskStatus", ctx, taskID)}
}

func (_c *MockTaskCoordinator_GetTaskStatus_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskCoordinator_GetTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskCoordinator_GetTaskStatus_Call) Return(_a0 *domain.Task, _a1 error) *MockTaskCoordinator_GetTaskStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskCoordinator_GetTaskStatus_Call) RunAndReturn(run func(context.Context, string) (*domain.Task, error)) *MockTaskCoordinator_GetTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTaskResult provides a mock function with given fields: ctx, taskID, result, errMsg
func (_m *MockTaskCoordinator) HandleTaskResult(ctx context.Context, taskID string, result string, errMsg string) error {
	ret := _m.Called(ctx, taskID, result, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for HandleTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, taskID, result, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCoordinator_HandleTaskResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTaskResult'
type MockTaskCoordinator_HandleTaskResult_Call struct {
	*mock.Call
}

// HandleTaskResult is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - result string
//   - errMsg string
func (_e *MockTaskCoordinator_Expecter) HandleTaskResult(ctx interface{}, taskID interface{}, result interface{}, errMsg interface{}) *MockTaskCoordinator_HandleTaskResult_Call {
	return &MockTaskCoordinator_HandleTaskResult_Call{Call: _e.mock.On("HandleTaskResult", ctx, taskID, result, errMsg)}
}

func (_c *MockTaskCoordinator_HandleTaskResult_Call) Run(run func(ctx context.Context, taskID string, result string, errMsg string)) *MockTaskCoordinator_HandleTaskResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTaskCoordinator_HandleTaskResult_Call) Return(_a0 error) *MockTaskCoordinator_HandleTaskResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCoordinator_HandleTaskResult_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTaskCoordinator_HandleTaskResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskCoordinator creates a new instance of MockTaskCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCoordinator {
	mock := &MockTaskCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
