// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockKeyManager

import mock "github.com/stretchr/testify/mock"

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

type MockKeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyManager) EXPECT() *MockKeyManager_Expecter {
	return &MockKeyManager_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ciphertext
func (_m *MockKeyManager) Decrypt(ciphertext string) (string, error) {
	ret := _m.Called(ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(ciphertext)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ciphertext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ciphertext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockKeyManager_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext string
func (_e *MockKeyManager_Expecter) Decrypt(ciphertext interface{}) *MockKeyManager_Decrypt_Call {
	return &MockKeyManager_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext)}
}

func (_c *MockKeyManager_Decrypt_Call) Run(run func(ciphertext string)) *MockKeyManager_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKeyManager_Decrypt_Call) Return(_a0 string, _a1 error) *MockKeyManager_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_Decrypt_Call) RunAndReturn(run func(string) (string, error)) *MockKeyManager_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *MockKeyManager) Encrypt(plaintext string) (string, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockKeyManager_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *MockKeyManager_Expecter) Encrypt(plaintext interface{}) *MockKeyManager_Encrypt_Call {
	return &MockKeyManager_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *MockKeyManager_Encrypt_Call) Run(run func(plaintext string)) *MockKeyManager_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKeyManager_Encrypt_Call) Return(_a0 string, _a1 error) *MockKeyManager_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_Encrypt_Call) RunAndReturn(run func(string) (string, error)) *MockKeyManager_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// IsLocked provides a mock function with no fields
func (_m *MockKeyManager) IsLocked() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLocked")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockKeyManager_IsLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocked'
type MockKeyManager_IsLocked_Call struct {
	*mock.Call
}

// IsLocked is a helper method to define mock.On call
func (_e *MockKeyManager_Expecter) IsLocked() *MockKeyManager_IsLocked_Call {
	return &MockKeyManager_IsLocked_Call{Call: _e.mock.On("IsLocked")}
}

func (_c *MockKeyManager_IsLocked_Call) Run(run func()) *MockKeyManager_IsLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyManager_IsLocked_Call) Return(_a0 bool) *MockKeyManager_IsLocked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyManager_IsLocked_Call) RunAndReturn(run func() bool) *MockKeyManager_IsLocked_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function with no fields
func (_m *MockKeyManager) Lock() {
	_m.Called()
}

// MockKeyManager_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockKeyManager_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
func (_e *MockKeyManager_Expecter) Lock() *MockKeyManager_Lock_Call {
	return &MockKeyManager_Lock_Call{Call: _e.mock.On("Lock")}
}

func (_c *MockKeyManager_Lock_Call) Run(run func()) *MockKeyManager_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyManager_Lock_Call) Return() *MockKeyManager_Lock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKeyManager_Lock_Call) RunAndReturn(run func()) *MockKeyManager_Lock_Call {
	_c.Run(run)
	return _c
}

// Unlock provides a mock function with given fields: masterKey
func (_m *MockKeyManager) Unlock(masterKey string) error {
	ret := _m.Called(masterKey)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(masterKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyManager_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockKeyManager_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - masterKey string
func (_e *MockKeyManager_Expecter) Unlock(masterKey interface{}) *MockKeyManager_Unlock_Call {
	return &MockKeyManager_Unlock_Call{Call: _e.mock.On("Unlock", masterKey)}
}

func (_c *MockKeyManager_Unlock_Call) Run(run func(masterKey string)) *MockKeyManager_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKeyManager_Unlock_Call) Return(_a0 error) *MockKeyManager_Unlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyManager_Unlock_Call) RunAndReturn(run func(string) error) *MockKeyManager_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyManager creates a new instance of MockKeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyManager {
	mock := &MockKeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
