/**
 * OpenHive Backend - Fastify Middleware Plugins
 *
 * Fastify plugin equivalents for the chi middleware stack:
 *   - requestIdPlugin     — generate UUID, set X-Request-ID header, decorate request
 *   - securityHeadersPlugin — security headers with WebSocket + Tailwind CSP
 *   - timingPlugin        — X-Response-Time header
 *   - structuredLoggingPlugin — pino + optional DB logging (level based on status code)
 *   - corsPlugin          — strict origin checking with OPTIONS preflight
 *   - panicRecoveryPlugin — catch unhandled errors, return 500 JSON
 *
 */

import { randomUUID } from 'crypto';

import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import fp from 'fastify-plugin';

import type { LogEntry } from '../domain/types.js';
import type { LogLevel } from '../domain/enums.js';
import { sendError } from './response.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Content-Security-Policy for servers that also serve the React SPA.
 * Allows Tailwind inline styles and WebSocket connections from the portal.
 */
const CSP_WITH_WS =
  "default-src 'self'; " +
  "style-src 'self' 'unsafe-inline'; " +
  "connect-src 'self' ws: wss:; " +
  "img-src 'self' data:";

// ---------------------------------------------------------------------------
// DBLogger interface
// ---------------------------------------------------------------------------

/**
 * Minimal write-only logger interface for persisting structured log entries.
 */
export interface DBLogger {
  log(entry: Omit<LogEntry, 'id'>): void;
}

// ---------------------------------------------------------------------------
// MiddlewareLogger interface
// ---------------------------------------------------------------------------

/** Pino-compatible logger subset used by middleware plugins. */
export interface MiddlewareLogger {
  info(msg: string, ...args: unknown[]): void;
  warn(msg: string, ...args: unknown[]): void;
  error(msg: string, ...args: unknown[]): void;
  debug(msg: string, ...args: unknown[]): void;
}

// ---------------------------------------------------------------------------
// Fastify type extension: request.id
// ---------------------------------------------------------------------------

declare module 'fastify' {
  interface FastifyRequest {
    /** UUID generated by requestIdPlugin for this request. */
    requestId: string;
  }
}

// ---------------------------------------------------------------------------
// requestIdPlugin
// ---------------------------------------------------------------------------

/**
 * Generates a UUID for each request, attaches it to `request.requestId`,
 * and sets the `X-Request-ID` response header.
 */
export const requestIdPlugin = fp(async (fastify: FastifyInstance) => {
  fastify.decorateRequest('requestId', '');

  fastify.addHook('onRequest', async (request: FastifyRequest, reply: FastifyReply) => {
    const id = randomUUID();
    request.requestId = id;
    reply.header('X-Request-ID', id);
  });
}, { name: 'request-id' });

// ---------------------------------------------------------------------------
// securityHeadersPlugin
// ---------------------------------------------------------------------------

/**
 * Sets security headers on all responses:
 *   X-Content-Type-Options: nosniff
 *   X-Frame-Options: DENY
 *   Content-Security-Policy: (WebSocket + Tailwind variant)
 */
export const securityHeadersPlugin = fp(async (fastify: FastifyInstance) => {
  fastify.addHook('onSend', (_request: FastifyRequest, reply: FastifyReply, _payload, done) => {
    reply.header('X-Content-Type-Options', 'nosniff');
    reply.header('X-Frame-Options', 'DENY');
    reply.header('Content-Security-Policy', CSP_WITH_WS);
    done();
  });
}, { name: 'security-headers' });

// ---------------------------------------------------------------------------
// timingPlugin
// ---------------------------------------------------------------------------

/**
 * Records request start time and sets `X-Response-Time` header on the response.
 */
export const timingPlugin = fp(async (fastify: FastifyInstance) => {
  fastify.addHook('onRequest', async (request: FastifyRequest) => {
    (request as FastifyRequest & { _startTime: number })._startTime = Date.now();
  });

  fastify.addHook('onSend', (request: FastifyRequest, reply: FastifyReply, _payload, done) => {
    const startTime = (request as FastifyRequest & { _startTime?: number })._startTime;
    if (startTime !== undefined) {
      const durationMs = Date.now() - startTime;
      reply.header('X-Response-Time', `${durationMs}ms`);
    }
    done();
  });
}, { name: 'timing' });

// ---------------------------------------------------------------------------
// structuredLoggingPlugin
// ---------------------------------------------------------------------------

/**
 * Logs each request to pino and optionally to a DBLogger.
 * Log level is derived from HTTP status:
 *   >= 500 → error
 *   >= 400 → warn
 *   otherwise → info
 */
export function structuredLoggingPlugin(
  logger: MiddlewareLogger,
  dbLogger?: DBLogger,
): (fastify: FastifyInstance) => Promise<void> {
  return fp(async (fastify: FastifyInstance) => {
    fastify.addHook(
      'onResponse',
      async (request: FastifyRequest, reply: FastifyReply) => {
        const status = reply.statusCode;
        const method = request.method;
        const path = request.url;
        const requestId = request.requestId ?? '';

        const startTime = (request as FastifyRequest & { _startTime?: number })._startTime;
        const durationMs = startTime !== undefined ? Date.now() - startTime : 0;

        const logMsg = `${method} ${path} ${status}`;

        if (status >= 500) {
          logger.error(logMsg, { requestId, method, path, status, durationMs });
        } else if (status >= 400) {
          logger.warn(logMsg, { requestId, method, path, status, durationMs });
        } else {
          logger.info(logMsg, { requestId, method, path, status, durationMs });
        }

        if (dbLogger !== undefined) {
          let level: LogLevel = 'info';
          if (status >= 500) {
            level = 'error';
          } else if (status >= 400) {
            level = 'warn';
          }

          dbLogger.log({
            level,
            component: 'api',
            action: `${method} ${path}`,
            message: logMsg,
            request_id: requestId,
            duration_ms: durationMs,
            created_at: new Date(),
          });
        }
      },
    );
  }, { name: 'structured-logging' });
}

// ---------------------------------------------------------------------------
// corsPlugin
// ---------------------------------------------------------------------------

/**
 * Enforces strict origin-based CORS. Only origins in the allowedOrigins list
 * receive Access-Control-Allow-Origin headers. Handles OPTIONS preflight.
 */
export function corsPlugin(
  allowedOrigins: string[],
): (fastify: FastifyInstance) => Promise<void> {
  const originSet = new Set(allowedOrigins.map((o) => o.trim()));

  return fp(async (fastify: FastifyInstance) => {
    fastify.addHook('onRequest', async (request: FastifyRequest, reply: FastifyReply) => {
      const origin = request.headers['origin'];

      if (typeof origin === 'string' && originSet.has(origin)) {
        reply.header('Access-Control-Allow-Origin', origin);
        reply.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
        reply.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
        reply.header('Access-Control-Allow-Credentials', 'true');
        reply.header('Vary', 'Origin');
      }

      // OPTIONS preflight: only respond for allowed origins.
      // reply.hijack() bypasses Fastify's routing/404 lifecycle so the raw
      // response is written directly — identical to the early-return in chi.
      if (
        request.method === 'OPTIONS' &&
        typeof origin === 'string' &&
        originSet.has(origin)
      ) {
        reply.hijack();
        reply.raw.writeHead(204, {
          'Access-Control-Allow-Origin': origin,
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE',
          'Access-Control-Allow-Headers': 'Content-Type, Authorization',
          'Access-Control-Allow-Credentials': 'true',
          'Vary': 'Origin',
        });
        reply.raw.end();
      }
    });
  }, { name: 'cors' });
}

// ---------------------------------------------------------------------------
// panicRecoveryPlugin
// ---------------------------------------------------------------------------

/**
 * Sets a Fastify error handler that logs unhandled errors and returns 500.
 * Fastify validation errors (schema failures) are surfaced as 400 VALIDATION_ERROR.
 */
export function panicRecoveryPlugin(
  logger: MiddlewareLogger,
): (fastify: FastifyInstance) => Promise<void> {
  return fp(async (fastify: FastifyInstance) => {
    fastify.setErrorHandler(
      (error: Error & { validation?: unknown; statusCode?: number }, request: FastifyRequest, reply: FastifyReply) => {
        const requestId = request.requestId ?? '';
        const replySend = reply as unknown as Parameters<typeof sendError>[0];

        // Fastify schema validation errors have a `validation` property and statusCode 400
        if (error.validation !== undefined || error.statusCode === 400) {
          logger.warn('validation error', {
            requestId,
            error: error.message,
          });
          sendError(replySend, 400, 'VALIDATION_ERROR', error.message);
          return;
        }

        // JSON parse errors from Fastify's content-type parser
        if (error.statusCode === 415 || (error as { code?: string }).code === 'FST_ERR_CTP_INVALID_MEDIA_TYPE') {
          sendError(replySend, 400, 'INVALID_REQUEST', 'unsupported content type');
          return;
        }

        logger.error('unhandled error', {
          requestId,
          error: error.message,
          stack: error.stack,
        });
        sendError(replySend, 500, 'INTERNAL_ERROR', 'an internal error occurred');
      },
    );
  }, { name: 'panic-recovery' });
}
