// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockWSConnection

import mock "github.com/stretchr/testify/mock"

// MockWSConnection is an autogenerated mock type for the WSConnection type
type MockWSConnection struct {
	mock.Mock
}

type MockWSConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWSConnection) EXPECT() *MockWSConnection_Expecter {
	return &MockWSConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockWSConnection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWSConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWSConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWSConnection_Expecter) Close() *MockWSConnection_Close_Call {
	return &MockWSConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWSConnection_Close_Call) Run(run func()) *MockWSConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWSConnection_Close_Call) Return(_a0 error) *MockWSConnection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSConnection_Close_Call) RunAndReturn(run func() error) *MockWSConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: msg
func (_m *MockWSConnection) Send(msg []byte) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWSConnection_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockWSConnection_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg []byte
func (_e *MockWSConnection_Expecter) Send(msg interface{}) *MockWSConnection_Send_Call {
	return &MockWSConnection_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *MockWSConnection_Send_Call) Run(run func(msg []byte)) *MockWSConnection_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockWSConnection_Send_Call) Return(_a0 error) *MockWSConnection_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSConnection_Send_Call) RunAndReturn(run func([]byte) error) *MockWSConnection_Send_Call {
	_c.Call.Return(run)
	return _c
}

// TeamID provides a mock function with no fields
func (_m *MockWSConnection) TeamID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TeamID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWSConnection_TeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamID'
type MockWSConnection_TeamID_Call struct {
	*mock.Call
}

// TeamID is a helper method to define mock.On call
func (_e *MockWSConnection_Expecter) TeamID() *MockWSConnection_TeamID_Call {
	return &MockWSConnection_TeamID_Call{Call: _e.mock.On("TeamID")}
}

func (_c *MockWSConnection_TeamID_Call) Run(run func()) *MockWSConnection_TeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWSConnection_TeamID_Call) Return(_a0 string) *MockWSConnection_TeamID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSConnection_TeamID_Call) RunAndReturn(run func() string) *MockWSConnection_TeamID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWSConnection creates a new instance of MockWSConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWSConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWSConnection {
	mock := &MockWSConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
