// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockEventBus

import (
	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: event
func (_m *MockEventBus) Publish(event domain.Event) {
	_m.Called(event)
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event domain.Event
func (_e *MockEventBus_Expecter) Publish(event interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(event domain.Event)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Event))
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return() *MockEventBus_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(domain.Event)) *MockEventBus_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function with given fields: eventType, handler
func (_m *MockEventBus) Subscribe(eventType domain.EventType, handler func(domain.Event)) string {
	ret := _m.Called(eventType, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.EventType, func(domain.Event)) string); ok {
		r0 = rf(eventType, handler)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - eventType domain.EventType
//   - handler func(domain.Event)
func (_e *MockEventBus_Expecter) Subscribe(eventType interface{}, handler interface{}) *MockEventBus_Subscribe_Call {
	return &MockEventBus_Subscribe_Call{Call: _e.mock.On("Subscribe", eventType, handler)}
}

func (_c *MockEventBus_Subscribe_Call) Run(run func(eventType domain.EventType, handler func(domain.Event))) *MockEventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.EventType), args[1].(func(domain.Event)))
	})
	return _c
}

func (_c *MockEventBus_Subscribe_Call) Return(_a0 string) *MockEventBus_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Subscribe_Call) RunAndReturn(run func(domain.EventType, func(domain.Event)) string) *MockEventBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: id
func (_m *MockEventBus) Unsubscribe(id string) {
	_m.Called(id)
}

// MockEventBus_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockEventBus_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - id string
func (_e *MockEventBus_Expecter) Unsubscribe(id interface{}) *MockEventBus_Unsubscribe_Call {
	return &MockEventBus_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", id)}
}

func (_c *MockEventBus_Unsubscribe_Call) Run(run func(id string)) *MockEventBus_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEventBus_Unsubscribe_Call) Return() *MockEventBus_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Unsubscribe_Call) RunAndReturn(run func(string)) *MockEventBus_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
