// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockWSHub

import (
	http "net/http"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockWSHub is an autogenerated mock type for the WSHub type
type MockWSHub struct {
	mock.Mock
}

type MockWSHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWSHub) EXPECT() *MockWSHub_Expecter {
	return &MockWSHub_Expecter{mock: &_m.Mock}
}

// BroadcastAll provides a mock function with given fields: msg
func (_m *MockWSHub) BroadcastAll(msg []byte) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWSHub_BroadcastAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastAll'
type MockWSHub_BroadcastAll_Call struct {
	*mock.Call
}

// BroadcastAll is a helper method to define mock.On call
//   - msg []byte
func (_e *MockWSHub_Expecter) BroadcastAll(msg interface{}) *MockWSHub_BroadcastAll_Call {
	return &MockWSHub_BroadcastAll_Call{Call: _e.mock.On("BroadcastAll", msg)}
}

func (_c *MockWSHub_BroadcastAll_Call) Run(run func(msg []byte)) *MockWSHub_BroadcastAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockWSHub_BroadcastAll_Call) Return(_a0 error) *MockWSHub_BroadcastAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSHub_BroadcastAll_Call) RunAndReturn(run func([]byte) error) *MockWSHub_BroadcastAll_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateToken provides a mock function with given fields: teamID
func (_m *MockWSHub) GenerateToken(teamID string) (string, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(teamID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWSHub_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockWSHub_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - teamID string
func (_e *MockWSHub_Expecter) GenerateToken(teamID interface{}) *MockWSHub_GenerateToken_Call {
	return &MockWSHub_GenerateToken_Call{Call: _e.mock.On("GenerateToken", teamID)}
}

func (_c *MockWSHub_GenerateToken_Call) Run(run func(teamID string)) *MockWSHub_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWSHub_GenerateToken_Call) Return(_a0 string, _a1 error) *MockWSHub_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWSHub_GenerateToken_Call) RunAndReturn(run func(string) (string, error)) *MockWSHub_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectedTeams provides a mock function with no fields
func (_m *MockWSHub) GetConnectedTeams() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectedTeams")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockWSHub_GetConnectedTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectedTeams'
type MockWSHub_GetConnectedTeams_Call struct {
	*mock.Call
}

// GetConnectedTeams is a helper method to define mock.On call
func (_e *MockWSHub_Expecter) GetConnectedTeams() *MockWSHub_GetConnectedTeams_Call {
	return &MockWSHub_GetConnectedTeams_Call{Call: _e.mock.On("GetConnectedTeams")}
}

func (_c *MockWSHub_GetConnectedTeams_Call) Run(run func()) *MockWSHub_GetConnectedTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWSHub_GetConnectedTeams_Call) Return(_a0 []string) *MockWSHub_GetConnectedTeams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSHub_GetConnectedTeams_Call) RunAndReturn(run func() []string) *MockWSHub_GetConnectedTeams_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpgrade provides a mock function with given fields: w, r
func (_m *MockWSHub) HandleUpgrade(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockWSHub_HandleUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpgrade'
type MockWSHub_HandleUpgrade_Call struct {
	*mock.Call
}

// HandleUpgrade is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockWSHub_Expecter) HandleUpgrade(w interface{}, r interface{}) *MockWSHub_HandleUpgrade_Call {
	return &MockWSHub_HandleUpgrade_Call{Call: _e.mock.On("HandleUpgrade", w, r)}
}

func (_c *MockWSHub_HandleUpgrade_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockWSHub_HandleUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockWSHub_HandleUpgrade_Call) Return() *MockWSHub_HandleUpgrade_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWSHub_HandleUpgrade_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockWSHub_HandleUpgrade_Call {
	_c.Run(run)
	return _c
}

// RegisterConnection provides a mock function with given fields: teamID, conn
func (_m *MockWSHub) RegisterConnection(teamID string, conn domain.WSConnection) error {
	ret := _m.Called(teamID, conn)

	if len(ret) == 0 {
		panic("no return value specified for RegisterConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.WSConnection) error); ok {
		r0 = rf(teamID, conn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWSHub_RegisterConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterConnection'
type MockWSHub_RegisterConnection_Call struct {
	*mock.Call
}

// RegisterConnection is a helper method to define mock.On call
//   - teamID string
//   - conn domain.WSConnection
func (_e *MockWSHub_Expecter) RegisterConnection(teamID interface{}, conn interface{}) *MockWSHub_RegisterConnection_Call {
	return &MockWSHub_RegisterConnection_Call{Call: _e.mock.On("RegisterConnection", teamID, conn)}
}

func (_c *MockWSHub_RegisterConnection_Call) Run(run func(teamID string, conn domain.WSConnection)) *MockWSHub_RegisterConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.WSConnection))
	})
	return _c
}

func (_c *MockWSHub_RegisterConnection_Call) Return(_a0 error) *MockWSHub_RegisterConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSHub_RegisterConnection_Call) RunAndReturn(run func(string, domain.WSConnection) error) *MockWSHub_RegisterConnection_Call {
	_c.Call.Return(run)
	return _c
}

// SendToTeam provides a mock function with given fields: teamID, msg
func (_m *MockWSHub) SendToTeam(teamID string, msg []byte) error {
	ret := _m.Called(teamID, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendToTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(teamID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWSHub_SendToTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToTeam'
type MockWSHub_SendToTeam_Call struct {
	*mock.Call
}

// SendToTeam is a helper method to define mock.On call
//   - teamID string
//   - msg []byte
func (_e *MockWSHub_Expecter) SendToTeam(teamID interface{}, msg interface{}) *MockWSHub_SendToTeam_Call {
	return &MockWSHub_SendToTeam_Call{Call: _e.mock.On("SendToTeam", teamID, msg)}
}

func (_c *MockWSHub_SendToTeam_Call) Run(run func(teamID string, msg []byte)) *MockWSHub_SendToTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockWSHub_SendToTeam_Call) Return(_a0 error) *MockWSHub_SendToTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWSHub_SendToTeam_Call) RunAndReturn(run func(string, []byte) error) *MockWSHub_SendToTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnConnect provides a mock function with given fields: handler
func (_m *MockWSHub) SetOnConnect(handler func(string)) {
	_m.Called(handler)
}

// MockWSHub_SetOnConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnConnect'
type MockWSHub_SetOnConnect_Call struct {
	*mock.Call
}

// SetOnConnect is a helper method to define mock.On call
//   - handler func(string)
func (_e *MockWSHub_Expecter) SetOnConnect(handler interface{}) *MockWSHub_SetOnConnect_Call {
	return &MockWSHub_SetOnConnect_Call{Call: _e.mock.On("SetOnConnect", handler)}
}

func (_c *MockWSHub_SetOnConnect_Call) Run(run func(handler func(string))) *MockWSHub_SetOnConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string)))
	})
	return _c
}

func (_c *MockWSHub_SetOnConnect_Call) Return() *MockWSHub_SetOnConnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWSHub_SetOnConnect_Call) RunAndReturn(run func(func(string))) *MockWSHub_SetOnConnect_Call {
	_c.Run(run)
	return _c
}

// SetOnMessage provides a mock function with given fields: handler
func (_m *MockWSHub) SetOnMessage(handler func(string, []byte)) {
	_m.Called(handler)
}

// MockWSHub_SetOnMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnMessage'
type MockWSHub_SetOnMessage_Call struct {
	*mock.Call
}

// SetOnMessage is a helper method to define mock.On call
//   - handler func(string , []byte)
func (_e *MockWSHub_Expecter) SetOnMessage(handler interface{}) *MockWSHub_SetOnMessage_Call {
	return &MockWSHub_SetOnMessage_Call{Call: _e.mock.On("SetOnMessage", handler)}
}

func (_c *MockWSHub_SetOnMessage_Call) Run(run func(handler func(string, []byte))) *MockWSHub_SetOnMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string, []byte)))
	})
	return _c
}

func (_c *MockWSHub_SetOnMessage_Call) Return() *MockWSHub_SetOnMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWSHub_SetOnMessage_Call) RunAndReturn(run func(func(string, []byte))) *MockWSHub_SetOnMessage_Call {
	_c.Run(run)
	return _c
}

// UnregisterConnection provides a mock function with given fields: teamID
func (_m *MockWSHub) UnregisterConnection(teamID string) {
	_m.Called(teamID)
}

// MockWSHub_UnregisterConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterConnection'
type MockWSHub_UnregisterConnection_Call struct {
	*mock.Call
}

// UnregisterConnection is a helper method to define mock.On call
//   - teamID string
func (_e *MockWSHub_Expecter) UnregisterConnection(teamID interface{}) *MockWSHub_UnregisterConnection_Call {
	return &MockWSHub_UnregisterConnection_Call{Call: _e.mock.On("UnregisterConnection", teamID)}
}

func (_c *MockWSHub_UnregisterConnection_Call) Run(run func(teamID string)) *MockWSHub_UnregisterConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWSHub_UnregisterConnection_Call) Return() *MockWSHub_UnregisterConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWSHub_UnregisterConnection_Call) RunAndReturn(run func(string)) *MockWSHub_UnregisterConnection_Call {
	_c.Run(run)
	return _c
}

// NewMockWSHub creates a new instance of MockWSHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWSHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWSHub {
	mock := &MockWSHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
