// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockSDKToolHandler

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// MockSDKToolHandler is an autogenerated mock type for the SDKToolHandler type
type MockSDKToolHandler struct {
	mock.Mock
}

type MockSDKToolHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSDKToolHandler) EXPECT() *MockSDKToolHandler_Expecter {
	return &MockSDKToolHandler_Expecter{mock: &_m.Mock}
}

// HandleToolCall provides a mock function with given fields: callID, toolName, args
func (_m *MockSDKToolHandler) HandleToolCall(callID string, toolName string, args json.RawMessage) (json.RawMessage, error) {
	ret := _m.Called(callID, toolName, args)

	if len(ret) == 0 {
		panic("no return value specified for HandleToolCall")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, json.RawMessage) (json.RawMessage, error)); ok {
		return rf(callID, toolName, args)
	}
	if rf, ok := ret.Get(0).(func(string, string, json.RawMessage) json.RawMessage); ok {
		r0 = rf(callID, toolName, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, json.RawMessage) error); ok {
		r1 = rf(callID, toolName, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSDKToolHandler_HandleToolCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleToolCall'
type MockSDKToolHandler_HandleToolCall_Call struct {
	*mock.Call
}

// HandleToolCall is a helper method to define mock.On call
//   - callID string
//   - toolName string
//   - args json.RawMessage
func (_e *MockSDKToolHandler_Expecter) HandleToolCall(callID interface{}, toolName interface{}, args interface{}) *MockSDKToolHandler_HandleToolCall_Call {
	return &MockSDKToolHandler_HandleToolCall_Call{Call: _e.mock.On("HandleToolCall", callID, toolName, args)}
}

func (_c *MockSDKToolHandler_HandleToolCall_Call) Run(run func(callID string, toolName string, args json.RawMessage)) *MockSDKToolHandler_HandleToolCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(json.RawMessage))
	})
	return _c
}

func (_c *MockSDKToolHandler_HandleToolCall_Call) Return(_a0 json.RawMessage, _a1 error) *MockSDKToolHandler_HandleToolCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSDKToolHandler_HandleToolCall_Call) RunAndReturn(run func(string, string, json.RawMessage) (json.RawMessage, error)) *MockSDKToolHandler_HandleToolCall_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSDKToolHandler creates a new instance of MockSDKToolHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSDKToolHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSDKToolHandler {
	mock := &MockSDKToolHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
