// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockTeamProvisioner

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamProvisioner is an autogenerated mock type for the TeamProvisioner type
type MockTeamProvisioner struct {
	mock.Mock
}

type MockTeamProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamProvisioner) EXPECT() *MockTeamProvisioner_Expecter {
	return &MockTeamProvisioner_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, slug, leaderAID
func (_m *MockTeamProvisioner) CreateTeam(ctx context.Context, slug string, leaderAID string) (*domain.Team, error) {
	ret := _m.Called(ctx, slug, leaderAID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Team, error)); ok {
		return rf(ctx, slug, leaderAID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Team); ok {
		r0 = rf(ctx, slug, leaderAID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, slug, leaderAID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamProvisioner_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamProvisioner_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - leaderAID string
func (_e *MockTeamProvisioner_Expecter) CreateTeam(ctx interface{}, slug interface{}, leaderAID interface{}) *MockTeamProvisioner_CreateTeam_Call {
	return &MockTeamProvisioner_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, slug, leaderAID)}
}

func (_c *MockTeamProvisioner_CreateTeam_Call) Run(run func(ctx context.Context, slug string, leaderAID string)) *MockTeamProvisioner_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTeamProvisioner_CreateTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamProvisioner_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamProvisioner_CreateTeam_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Team, error)) *MockTeamProvisioner_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, slug
func (_m *MockTeamProvisioner) DeleteTeam(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamProvisioner_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockTeamProvisioner_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockTeamProvisioner_Expecter) DeleteTeam(ctx interface{}, slug interface{}) *MockTeamProvisioner_DeleteTeam_Call {
	return &MockTeamProvisioner_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, slug)}
}

func (_c *MockTeamProvisioner_DeleteTeam_Call) Run(run func(ctx context.Context, slug string)) *MockTeamProvisioner_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamProvisioner_DeleteTeam_Call) Return(_a0 error) *MockTeamProvisioner_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamProvisioner_DeleteTeam_Call) RunAndReturn(run func(context.Context, string) error) *MockTeamProvisioner_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, slug
func (_m *MockTeamProvisioner) GetTeam(ctx context.Context, slug string) (*domain.Team, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamProvisioner_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamProvisioner_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockTeamProvisioner_Expecter) GetTeam(ctx interface{}, slug interface{}) *MockTeamProvisioner_GetTeam_Call {
	return &MockTeamProvisioner_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, slug)}
}

func (_c *MockTeamProvisioner_GetTeam_Call) Run(run func(ctx context.Context, slug string)) *MockTeamProvisioner_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamProvisioner_GetTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamProvisioner_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamProvisioner_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*domain.Team, error)) *MockTeamProvisioner_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *MockTeamProvisioner) ListTeams(ctx context.Context) ([]*domain.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []*domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamProvisioner_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockTeamProvisioner_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamProvisioner_Expecter) ListTeams(ctx interface{}) *MockTeamProvisioner_ListTeams_Call {
	return &MockTeamProvisioner_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *MockTeamProvisioner_ListTeams_Call) Run(run func(ctx context.Context)) *MockTeamProvisioner_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTeamProvisioner_ListTeams_Call) Return(_a0 []*domain.Team, _a1 error) *MockTeamProvisioner_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamProvisioner_ListTeams_Call) RunAndReturn(run func(context.Context) ([]*domain.Team, error)) *MockTeamProvisioner_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeam provides a mock function with given fields: ctx, slug, updates
func (_m *MockTeamProvisioner) UpdateTeam(ctx context.Context, slug string, updates map[string]interface{}) (*domain.Team, error) {
	ret := _m.Called(ctx, slug, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (*domain.Team, error)); ok {
		return rf(ctx, slug, updates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) *domain.Team); ok {
		r0 = rf(ctx, slug, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, slug, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamProvisioner_UpdateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeam'
type MockTeamProvisioner_UpdateTeam_Call struct {
	*mock.Call
}

// UpdateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - updates map[string]interface{}
func (_e *MockTeamProvisioner_Expecter) UpdateTeam(ctx interface{}, slug interface{}, updates interface{}) *MockTeamProvisioner_UpdateTeam_Call {
	return &MockTeamProvisioner_UpdateTeam_Call{Call: _e.mock.On("UpdateTeam", ctx, slug, updates)}
}

func (_c *MockTeamProvisioner_UpdateTeam_Call) Run(run func(ctx context.Context, slug string, updates map[string]interface{})) *MockTeamProvisioner_UpdateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockTeamProvisioner_UpdateTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamProvisioner_UpdateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamProvisioner_UpdateTeam_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (*domain.Team, error)) *MockTeamProvisioner_UpdateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamProvisioner creates a new instance of MockTeamProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamProvisioner {
	mock := &MockTeamProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
