// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockConfigLoader

import (
	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigLoader is an autogenerated mock type for the ConfigLoader type
type MockConfigLoader struct {
	mock.Mock
}

type MockConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigLoader) EXPECT() *MockConfigLoader_Expecter {
	return &MockConfigLoader_Expecter{mock: &_m.Mock}
}

// CreateTeamDir provides a mock function with given fields: slug
func (_m *MockConfigLoader) CreateTeamDir(slug string) error {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_CreateTeamDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamDir'
type MockConfigLoader_CreateTeamDir_Call struct {
	*mock.Call
}

// CreateTeamDir is a helper method to define mock.On call
//   - slug string
func (_e *MockConfigLoader_Expecter) CreateTeamDir(slug interface{}) *MockConfigLoader_CreateTeamDir_Call {
	return &MockConfigLoader_CreateTeamDir_Call{Call: _e.mock.On("CreateTeamDir", slug)}
}

func (_c *MockConfigLoader_CreateTeamDir_Call) Run(run func(slug string)) *MockConfigLoader_CreateTeamDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_CreateTeamDir_Call) Return(_a0 error) *MockConfigLoader_CreateTeamDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_CreateTeamDir_Call) RunAndReturn(run func(string) error) *MockConfigLoader_CreateTeamDir_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeamDir provides a mock function with given fields: slug
func (_m *MockConfigLoader) DeleteTeamDir(slug string) error {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeamDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_DeleteTeamDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeamDir'
type MockConfigLoader_DeleteTeamDir_Call struct {
	*mock.Call
}

// DeleteTeamDir is a helper method to define mock.On call
//   - slug string
func (_e *MockConfigLoader_Expecter) DeleteTeamDir(slug interface{}) *MockConfigLoader_DeleteTeamDir_Call {
	return &MockConfigLoader_DeleteTeamDir_Call{Call: _e.mock.On("DeleteTeamDir", slug)}
}

func (_c *MockConfigLoader_DeleteTeamDir_Call) Run(run func(slug string)) *MockConfigLoader_DeleteTeamDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_DeleteTeamDir_Call) Return(_a0 error) *MockConfigLoader_DeleteTeamDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_DeleteTeamDir_Call) RunAndReturn(run func(string) error) *MockConfigLoader_DeleteTeamDir_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with no fields
func (_m *MockConfigLoader) ListTeams() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockConfigLoader_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
func (_e *MockConfigLoader_Expecter) ListTeams() *MockConfigLoader_ListTeams_Call {
	return &MockConfigLoader_ListTeams_Call{Call: _e.mock.On("ListTeams")}
}

func (_c *MockConfigLoader_ListTeams_Call) Run(run func()) *MockConfigLoader_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigLoader_ListTeams_Call) Return(_a0 []string, _a1 error) *MockConfigLoader_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_ListTeams_Call) RunAndReturn(run func() ([]string, error)) *MockConfigLoader_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// LoadMaster provides a mock function with no fields
func (_m *MockConfigLoader) LoadMaster() (*domain.MasterConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadMaster")
	}

	var r0 *domain.MasterConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.MasterConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.MasterConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MasterConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_LoadMaster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadMaster'
type MockConfigLoader_LoadMaster_Call struct {
	*mock.Call
}

// LoadMaster is a helper method to define mock.On call
func (_e *MockConfigLoader_Expecter) LoadMaster() *MockConfigLoader_LoadMaster_Call {
	return &MockConfigLoader_LoadMaster_Call{Call: _e.mock.On("LoadMaster")}
}

func (_c *MockConfigLoader_LoadMaster_Call) Run(run func()) *MockConfigLoader_LoadMaster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigLoader_LoadMaster_Call) Return(_a0 *domain.MasterConfig, _a1 error) *MockConfigLoader_LoadMaster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_LoadMaster_Call) RunAndReturn(run func() (*domain.MasterConfig, error)) *MockConfigLoader_LoadMaster_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProviders provides a mock function with no fields
func (_m *MockConfigLoader) LoadProviders() (map[string]domain.Provider, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadProviders")
	}

	var r0 map[string]domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]domain.Provider, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]domain.Provider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_LoadProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProviders'
type MockConfigLoader_LoadProviders_Call struct {
	*mock.Call
}

// LoadProviders is a helper method to define mock.On call
func (_e *MockConfigLoader_Expecter) LoadProviders() *MockConfigLoader_LoadProviders_Call {
	return &MockConfigLoader_LoadProviders_Call{Call: _e.mock.On("LoadProviders")}
}

func (_c *MockConfigLoader_LoadProviders_Call) Run(run func()) *MockConfigLoader_LoadProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigLoader_LoadProviders_Call) Return(_a0 map[string]domain.Provider, _a1 error) *MockConfigLoader_LoadProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_LoadProviders_Call) RunAndReturn(run func() (map[string]domain.Provider, error)) *MockConfigLoader_LoadProviders_Call {
	_c.Call.Return(run)
	return _c
}

// LoadTeam provides a mock function with given fields: slug
func (_m *MockConfigLoader) LoadTeam(slug string) (*domain.Team, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for LoadTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Team, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Team); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_LoadTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTeam'
type MockConfigLoader_LoadTeam_Call struct {
	*mock.Call
}

// LoadTeam is a helper method to define mock.On call
//   - slug string
func (_e *MockConfigLoader_Expecter) LoadTeam(slug interface{}) *MockConfigLoader_LoadTeam_Call {
	return &MockConfigLoader_LoadTeam_Call{Call: _e.mock.On("LoadTeam", slug)}
}

func (_c *MockConfigLoader_LoadTeam_Call) Run(run func(slug string)) *MockConfigLoader_LoadTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_LoadTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockConfigLoader_LoadTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_LoadTeam_Call) RunAndReturn(run func(string) (*domain.Team, error)) *MockConfigLoader_LoadTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMaster provides a mock function with given fields: cfg
func (_m *MockConfigLoader) SaveMaster(cfg *domain.MasterConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for SaveMaster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MasterConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_SaveMaster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMaster'
type MockConfigLoader_SaveMaster_Call struct {
	*mock.Call
}

// SaveMaster is a helper method to define mock.On call
//   - cfg *domain.MasterConfig
func (_e *MockConfigLoader_Expecter) SaveMaster(cfg interface{}) *MockConfigLoader_SaveMaster_Call {
	return &MockConfigLoader_SaveMaster_Call{Call: _e.mock.On("SaveMaster", cfg)}
}

func (_c *MockConfigLoader_SaveMaster_Call) Run(run func(cfg *domain.MasterConfig)) *MockConfigLoader_SaveMaster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.MasterConfig))
	})
	return _c
}

func (_c *MockConfigLoader_SaveMaster_Call) Return(_a0 error) *MockConfigLoader_SaveMaster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_SaveMaster_Call) RunAndReturn(run func(*domain.MasterConfig) error) *MockConfigLoader_SaveMaster_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProviders provides a mock function with given fields: providers
func (_m *MockConfigLoader) SaveProviders(providers map[string]domain.Provider) error {
	ret := _m.Called(providers)

	if len(ret) == 0 {
		panic("no return value specified for SaveProviders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]domain.Provider) error); ok {
		r0 = rf(providers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_SaveProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProviders'
type MockConfigLoader_SaveProviders_Call struct {
	*mock.Call
}

// SaveProviders is a helper method to define mock.On call
//   - providers map[string]domain.Provider
func (_e *MockConfigLoader_Expecter) SaveProviders(providers interface{}) *MockConfigLoader_SaveProviders_Call {
	return &MockConfigLoader_SaveProviders_Call{Call: _e.mock.On("SaveProviders", providers)}
}

func (_c *MockConfigLoader_SaveProviders_Call) Run(run func(providers map[string]domain.Provider)) *MockConfigLoader_SaveProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]domain.Provider))
	})
	return _c
}

func (_c *MockConfigLoader_SaveProviders_Call) Return(_a0 error) *MockConfigLoader_SaveProviders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_SaveProviders_Call) RunAndReturn(run func(map[string]domain.Provider) error) *MockConfigLoader_SaveProviders_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTeam provides a mock function with given fields: slug, team
func (_m *MockConfigLoader) SaveTeam(slug string, team *domain.Team) error {
	ret := _m.Called(slug, team)

	if len(ret) == 0 {
		panic("no return value specified for SaveTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *domain.Team) error); ok {
		r0 = rf(slug, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_SaveTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTeam'
type MockConfigLoader_SaveTeam_Call struct {
	*mock.Call
}

// SaveTeam is a helper method to define mock.On call
//   - slug string
//   - team *domain.Team
func (_e *MockConfigLoader_Expecter) SaveTeam(slug interface{}, team interface{}) *MockConfigLoader_SaveTeam_Call {
	return &MockConfigLoader_SaveTeam_Call{Call: _e.mock.On("SaveTeam", slug, team)}
}

func (_c *MockConfigLoader_SaveTeam_Call) Run(run func(slug string, team *domain.Team)) *MockConfigLoader_SaveTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*domain.Team))
	})
	return _c
}

func (_c *MockConfigLoader_SaveTeam_Call) Return(_a0 error) *MockConfigLoader_SaveTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_SaveTeam_Call) RunAndReturn(run func(string, *domain.Team) error) *MockConfigLoader_SaveTeam_Call {
	_c.Call.Return(run)
	return _c
}

// StopWatching provides a mock function with no fields
func (_m *MockConfigLoader) StopWatching() {
	_m.Called()
}

// MockConfigLoader_StopWatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWatching'
type MockConfigLoader_StopWatching_Call struct {
	*mock.Call
}

// StopWatching is a helper method to define mock.On call
func (_e *MockConfigLoader_Expecter) StopWatching() *MockConfigLoader_StopWatching_Call {
	return &MockConfigLoader_StopWatching_Call{Call: _e.mock.On("StopWatching")}
}

func (_c *MockConfigLoader_StopWatching_Call) Run(run func()) *MockConfigLoader_StopWatching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigLoader_StopWatching_Call) Return() *MockConfigLoader_StopWatching_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigLoader_StopWatching_Call) RunAndReturn(run func()) *MockConfigLoader_StopWatching_Call {
	_c.Run(run)
	return _c
}

// WatchMaster provides a mock function with given fields: callback
func (_m *MockConfigLoader) WatchMaster(callback func(*domain.MasterConfig)) error {
	ret := _m.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for WatchMaster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*domain.MasterConfig)) error); ok {
		r0 = rf(callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_WatchMaster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchMaster'
type MockConfigLoader_WatchMaster_Call struct {
	*mock.Call
}

// WatchMaster is a helper method to define mock.On call
//   - callback func(*domain.MasterConfig)
func (_e *MockConfigLoader_Expecter) WatchMaster(callback interface{}) *MockConfigLoader_WatchMaster_Call {
	return &MockConfigLoader_WatchMaster_Call{Call: _e.mock.On("WatchMaster", callback)}
}

func (_c *MockConfigLoader_WatchMaster_Call) Run(run func(callback func(*domain.MasterConfig))) *MockConfigLoader_WatchMaster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*domain.MasterConfig)))
	})
	return _c
}

func (_c *MockConfigLoader_WatchMaster_Call) Return(_a0 error) *MockConfigLoader_WatchMaster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_WatchMaster_Call) RunAndReturn(run func(func(*domain.MasterConfig)) error) *MockConfigLoader_WatchMaster_Call {
	_c.Call.Return(run)
	return _c
}

// WatchProviders provides a mock function with given fields: callback
func (_m *MockConfigLoader) WatchProviders(callback func(map[string]domain.Provider)) error {
	ret := _m.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for WatchProviders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(map[string]domain.Provider)) error); ok {
		r0 = rf(callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_WatchProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchProviders'
type MockConfigLoader_WatchProviders_Call struct {
	*mock.Call
}

// WatchProviders is a helper method to define mock.On call
//   - callback func(map[string]domain.Provider)
func (_e *MockConfigLoader_Expecter) WatchProviders(callback interface{}) *MockConfigLoader_WatchProviders_Call {
	return &MockConfigLoader_WatchProviders_Call{Call: _e.mock.On("WatchProviders", callback)}
}

func (_c *MockConfigLoader_WatchProviders_Call) Run(run func(callback func(map[string]domain.Provider))) *MockConfigLoader_WatchProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(map[string]domain.Provider)))
	})
	return _c
}

func (_c *MockConfigLoader_WatchProviders_Call) Return(_a0 error) *MockConfigLoader_WatchProviders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_WatchProviders_Call) RunAndReturn(run func(func(map[string]domain.Provider)) error) *MockConfigLoader_WatchProviders_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTeam provides a mock function with given fields: slug, callback
func (_m *MockConfigLoader) WatchTeam(slug string, callback func(*domain.Team)) error {
	ret := _m.Called(slug, callback)

	if len(ret) == 0 {
		panic("no return value specified for WatchTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(*domain.Team)) error); ok {
		r0 = rf(slug, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_WatchTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTeam'
type MockConfigLoader_WatchTeam_Call struct {
	*mock.Call
}

// WatchTeam is a helper method to define mock.On call
//   - slug string
//   - callback func(*domain.Team)
func (_e *MockConfigLoader_Expecter) WatchTeam(slug interface{}, callback interface{}) *MockConfigLoader_WatchTeam_Call {
	return &MockConfigLoader_WatchTeam_Call{Call: _e.mock.On("WatchTeam", slug, callback)}
}

func (_c *MockConfigLoader_WatchTeam_Call) Run(run func(slug string, callback func(*domain.Team))) *MockConfigLoader_WatchTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(*domain.Team)))
	})
	return _c
}

func (_c *MockConfigLoader_WatchTeam_Call) Return(_a0 error) *MockConfigLoader_WatchTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_WatchTeam_Call) RunAndReturn(run func(string, func(*domain.Team)) error) *MockConfigLoader_WatchTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigLoader creates a new instance of MockConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigLoader {
	mock := &MockConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
