// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockChannelAdapter

import mock "github.com/stretchr/testify/mock"

// MockChannelAdapter is an autogenerated mock type for the ChannelAdapter type
type MockChannelAdapter struct {
	mock.Mock
}

type MockChannelAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelAdapter) EXPECT() *MockChannelAdapter_Expecter {
	return &MockChannelAdapter_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with no fields
func (_m *MockChannelAdapter) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelAdapter_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockChannelAdapter_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockChannelAdapter_Expecter) Connect() *MockChannelAdapter_Connect_Call {
	return &MockChannelAdapter_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockChannelAdapter_Connect_Call) Run(run func()) *MockChannelAdapter_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelAdapter_Connect_Call) Return(_a0 error) *MockChannelAdapter_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAdapter_Connect_Call) RunAndReturn(run func() error) *MockChannelAdapter_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *MockChannelAdapter) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelAdapter_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockChannelAdapter_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *MockChannelAdapter_Expecter) Disconnect() *MockChannelAdapter_Disconnect_Call {
	return &MockChannelAdapter_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *MockChannelAdapter_Disconnect_Call) Run(run func()) *MockChannelAdapter_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelAdapter_Disconnect_Call) Return(_a0 error) *MockChannelAdapter_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAdapter_Disconnect_Call) RunAndReturn(run func() error) *MockChannelAdapter_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetJIDPrefix provides a mock function with no fields
func (_m *MockChannelAdapter) GetJIDPrefix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJIDPrefix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChannelAdapter_GetJIDPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJIDPrefix'
type MockChannelAdapter_GetJIDPrefix_Call struct {
	*mock.Call
}

// GetJIDPrefix is a helper method to define mock.On call
func (_e *MockChannelAdapter_Expecter) GetJIDPrefix() *MockChannelAdapter_GetJIDPrefix_Call {
	return &MockChannelAdapter_GetJIDPrefix_Call{Call: _e.mock.On("GetJIDPrefix")}
}

func (_c *MockChannelAdapter_GetJIDPrefix_Call) Run(run func()) *MockChannelAdapter_GetJIDPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelAdapter_GetJIDPrefix_Call) Return(_a0 string) *MockChannelAdapter_GetJIDPrefix_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAdapter_GetJIDPrefix_Call) RunAndReturn(run func() string) *MockChannelAdapter_GetJIDPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *MockChannelAdapter) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockChannelAdapter_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockChannelAdapter_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockChannelAdapter_Expecter) IsConnected() *MockChannelAdapter_IsConnected_Call {
	return &MockChannelAdapter_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockChannelAdapter_IsConnected_Call) Run(run func()) *MockChannelAdapter_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelAdapter_IsConnected_Call) Return(_a0 bool) *MockChannelAdapter_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAdapter_IsConnected_Call) RunAndReturn(run func() bool) *MockChannelAdapter_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// OnMessage provides a mock function with given fields: callback
func (_m *MockChannelAdapter) OnMessage(callback func(string, string)) {
	_m.Called(callback)
}

// MockChannelAdapter_OnMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnMessage'
type MockChannelAdapter_OnMessage_Call struct {
	*mock.Call
}

// OnMessage is a helper method to define mock.On call
//   - callback func(string , string)
func (_e *MockChannelAdapter_Expecter) OnMessage(callback interface{}) *MockChannelAdapter_OnMessage_Call {
	return &MockChannelAdapter_OnMessage_Call{Call: _e.mock.On("OnMessage", callback)}
}

func (_c *MockChannelAdapter_OnMessage_Call) Run(run func(callback func(string, string))) *MockChannelAdapter_OnMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string, string)))
	})
	return _c
}

func (_c *MockChannelAdapter_OnMessage_Call) Return() *MockChannelAdapter_OnMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChannelAdapter_OnMessage_Call) RunAndReturn(run func(func(string, string))) *MockChannelAdapter_OnMessage_Call {
	_c.Run(run)
	return _c
}

// OnMetadata provides a mock function with given fields: callback
func (_m *MockChannelAdapter) OnMetadata(callback func(string, map[string]string)) {
	_m.Called(callback)
}

// MockChannelAdapter_OnMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnMetadata'
type MockChannelAdapter_OnMetadata_Call struct {
	*mock.Call
}

// OnMetadata is a helper method to define mock.On call
//   - callback func(string , map[string]string)
func (_e *MockChannelAdapter_Expecter) OnMetadata(callback interface{}) *MockChannelAdapter_OnMetadata_Call {
	return &MockChannelAdapter_OnMetadata_Call{Call: _e.mock.On("OnMetadata", callback)}
}

func (_c *MockChannelAdapter_OnMetadata_Call) Run(run func(callback func(string, map[string]string))) *MockChannelAdapter_OnMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string, map[string]string)))
	})
	return _c
}

func (_c *MockChannelAdapter_OnMetadata_Call) Return() *MockChannelAdapter_OnMetadata_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChannelAdapter_OnMetadata_Call) RunAndReturn(run func(func(string, map[string]string))) *MockChannelAdapter_OnMetadata_Call {
	_c.Run(run)
	return _c
}

// SendMessage provides a mock function with given fields: jid, content
func (_m *MockChannelAdapter) SendMessage(jid string, content string) error {
	ret := _m.Called(jid, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(jid, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelAdapter_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockChannelAdapter_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - jid string
//   - content string
func (_e *MockChannelAdapter_Expecter) SendMessage(jid interface{}, content interface{}) *MockChannelAdapter_SendMessage_Call {
	return &MockChannelAdapter_SendMessage_Call{Call: _e.mock.On("SendMessage", jid, content)}
}

func (_c *MockChannelAdapter_SendMessage_Call) Run(run func(jid string, content string)) *MockChannelAdapter_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChannelAdapter_SendMessage_Call) Return(_a0 error) *MockChannelAdapter_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAdapter_SendMessage_Call) RunAndReturn(run func(string, string) error) *MockChannelAdapter_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannelAdapter creates a new instance of MockChannelAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelAdapter {
	mock := &MockChannelAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
