// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockOrgChart

import (
	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOrgChart is an autogenerated mock type for the OrgChart type
type MockOrgChart struct {
	mock.Mock
}

type MockOrgChart_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrgChart) EXPECT() *MockOrgChart_Expecter {
	return &MockOrgChart_Expecter{mock: &_m.Mock}
}

// GetAgentByAID provides a mock function with given fields: aid
func (_m *MockOrgChart) GetAgentByAID(aid string) (*domain.Agent, error) {
	ret := _m.Called(aid)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentByAID")
	}

	var r0 *domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Agent, error)); ok {
		return rf(aid)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Agent); ok {
		r0 = rf(aid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetAgentByAID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentByAID'
type MockOrgChart_GetAgentByAID_Call struct {
	*mock.Call
}

// GetAgentByAID is a helper method to define mock.On call
//   - aid string
func (_e *MockOrgChart_Expecter) GetAgentByAID(aid interface{}) *MockOrgChart_GetAgentByAID_Call {
	return &MockOrgChart_GetAgentByAID_Call{Call: _e.mock.On("GetAgentByAID", aid)}
}

func (_c *MockOrgChart_GetAgentByAID_Call) Run(run func(aid string)) *MockOrgChart_GetAgentByAID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetAgentByAID_Call) Return(_a0 *domain.Agent, _a1 error) *MockOrgChart_GetAgentByAID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetAgentByAID_Call) RunAndReturn(run func(string) (*domain.Agent, error)) *MockOrgChart_GetAgentByAID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeadTeams provides a mock function with given fields: aid
func (_m *MockOrgChart) GetLeadTeams(aid string) ([]string, error) {
	ret := _m.Called(aid)

	if len(ret) == 0 {
		panic("no return value specified for GetLeadTeams")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(aid)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(aid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetLeadTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeadTeams'
type MockOrgChart_GetLeadTeams_Call struct {
	*mock.Call
}

// GetLeadTeams is a helper method to define mock.On call
//   - aid string
func (_e *MockOrgChart_Expecter) GetLeadTeams(aid interface{}) *MockOrgChart_GetLeadTeams_Call {
	return &MockOrgChart_GetLeadTeams_Call{Call: _e.mock.On("GetLeadTeams", aid)}
}

func (_c *MockOrgChart_GetLeadTeams_Call) Run(run func(aid string)) *MockOrgChart_GetLeadTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetLeadTeams_Call) Return(_a0 []string, _a1 error) *MockOrgChart_GetLeadTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetLeadTeams_Call) RunAndReturn(run func(string) ([]string, error)) *MockOrgChart_GetLeadTeams_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgChart provides a mock function with no fields
func (_m *MockOrgChart) GetOrgChart() map[string]*domain.Team {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrgChart")
	}

	var r0 map[string]*domain.Team
	if rf, ok := ret.Get(0).(func() map[string]*domain.Team); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.Team)
		}
	}

	return r0
}

// MockOrgChart_GetOrgChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgChart'
type MockOrgChart_GetOrgChart_Call struct {
	*mock.Call
}

// GetOrgChart is a helper method to define mock.On call
func (_e *MockOrgChart_Expecter) GetOrgChart() *MockOrgChart_GetOrgChart_Call {
	return &MockOrgChart_GetOrgChart_Call{Call: _e.mock.On("GetOrgChart")}
}

func (_c *MockOrgChart_GetOrgChart_Call) Run(run func()) *MockOrgChart_GetOrgChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrgChart_GetOrgChart_Call) Return(_a0 map[string]*domain.Team) *MockOrgChart_GetOrgChart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrgChart_GetOrgChart_Call) RunAndReturn(run func() map[string]*domain.Team) *MockOrgChart_GetOrgChart_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubordinates provides a mock function with given fields: aid
func (_m *MockOrgChart) GetSubordinates(aid string) ([]domain.Agent, error) {
	ret := _m.Called(aid)

	if len(ret) == 0 {
		panic("no return value specified for GetSubordinates")
	}

	var r0 []domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Agent, error)); ok {
		return rf(aid)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Agent); ok {
		r0 = rf(aid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetSubordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubordinates'
type MockOrgChart_GetSubordinates_Call struct {
	*mock.Call
}

// GetSubordinates is a helper method to define mock.On call
//   - aid string
func (_e *MockOrgChart_Expecter) GetSubordinates(aid interface{}) *MockOrgChart_GetSubordinates_Call {
	return &MockOrgChart_GetSubordinates_Call{Call: _e.mock.On("GetSubordinates", aid)}
}

func (_c *MockOrgChart_GetSubordinates_Call) Run(run func(aid string)) *MockOrgChart_GetSubordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetSubordinates_Call) Return(_a0 []domain.Agent, _a1 error) *MockOrgChart_GetSubordinates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetSubordinates_Call) RunAndReturn(run func(string) ([]domain.Agent, error)) *MockOrgChart_GetSubordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupervisor provides a mock function with given fields: aid
func (_m *MockOrgChart) GetSupervisor(aid string) (*domain.Agent, error) {
	ret := _m.Called(aid)

	if len(ret) == 0 {
		panic("no return value specified for GetSupervisor")
	}

	var r0 *domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Agent, error)); ok {
		return rf(aid)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Agent); ok {
		r0 = rf(aid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetSupervisor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupervisor'
type MockOrgChart_GetSupervisor_Call struct {
	*mock.Call
}

// GetSupervisor is a helper method to define mock.On call
//   - aid string
func (_e *MockOrgChart_Expecter) GetSupervisor(aid interface{}) *MockOrgChart_GetSupervisor_Call {
	return &MockOrgChart_GetSupervisor_Call{Call: _e.mock.On("GetSupervisor", aid)}
}

func (_c *MockOrgChart_GetSupervisor_Call) Run(run func(aid string)) *MockOrgChart_GetSupervisor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetSupervisor_Call) Return(_a0 *domain.Agent, _a1 error) *MockOrgChart_GetSupervisor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetSupervisor_Call) RunAndReturn(run func(string) (*domain.Agent, error)) *MockOrgChart_GetSupervisor_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamBySlug provides a mock function with given fields: slug
func (_m *MockOrgChart) GetTeamBySlug(slug string) (*domain.Team, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamBySlug")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Team, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Team); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetTeamBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamBySlug'
type MockOrgChart_GetTeamBySlug_Call struct {
	*mock.Call
}

// GetTeamBySlug is a helper method to define mock.On call
//   - slug string
func (_e *MockOrgChart_Expecter) GetTeamBySlug(slug interface{}) *MockOrgChart_GetTeamBySlug_Call {
	return &MockOrgChart_GetTeamBySlug_Call{Call: _e.mock.On("GetTeamBySlug", slug)}
}

func (_c *MockOrgChart_GetTeamBySlug_Call) Run(run func(slug string)) *MockOrgChart_GetTeamBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetTeamBySlug_Call) Return(_a0 *domain.Team, _a1 error) *MockOrgChart_GetTeamBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetTeamBySlug_Call) RunAndReturn(run func(string) (*domain.Team, error)) *MockOrgChart_GetTeamBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamForAgent provides a mock function with given fields: aid
func (_m *MockOrgChart) GetTeamForAgent(aid string) (*domain.Team, error) {
	ret := _m.Called(aid)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamForAgent")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Team, error)); ok {
		return rf(aid)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Team); ok {
		r0 = rf(aid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgChart_GetTeamForAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamForAgent'
type MockOrgChart_GetTeamForAgent_Call struct {
	*mock.Call
}

// GetTeamForAgent is a helper method to define mock.On call
//   - aid string
func (_e *MockOrgChart_Expecter) GetTeamForAgent(aid interface{}) *MockOrgChart_GetTeamForAgent_Call {
	return &MockOrgChart_GetTeamForAgent_Call{Call: _e.mock.On("GetTeamForAgent", aid)}
}

func (_c *MockOrgChart_GetTeamForAgent_Call) Run(run func(aid string)) *MockOrgChart_GetTeamForAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrgChart_GetTeamForAgent_Call) Return(_a0 *domain.Team, _a1 error) *MockOrgChart_GetTeamForAgent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgChart_GetTeamForAgent_Call) RunAndReturn(run func(string) (*domain.Team, error)) *MockOrgChart_GetTeamForAgent_Call {
	_c.Call.Return(run)
	return _c
}

// RebuildFromConfig provides a mock function with given fields: master, teams
func (_m *MockOrgChart) RebuildFromConfig(master *domain.MasterConfig, teams map[string]*domain.Team) error {
	ret := _m.Called(master, teams)

	if len(ret) == 0 {
		panic("no return value specified for RebuildFromConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MasterConfig, map[string]*domain.Team) error); ok {
		r0 = rf(master, teams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrgChart_RebuildFromConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebuildFromConfig'
type MockOrgChart_RebuildFromConfig_Call struct {
	*mock.Call
}

// RebuildFromConfig is a helper method to define mock.On call
//   - master *domain.MasterConfig
//   - teams map[string]*domain.Team
func (_e *MockOrgChart_Expecter) RebuildFromConfig(master interface{}, teams interface{}) *MockOrgChart_RebuildFromConfig_Call {
	return &MockOrgChart_RebuildFromConfig_Call{Call: _e.mock.On("RebuildFromConfig", master, teams)}
}

func (_c *MockOrgChart_RebuildFromConfig_Call) Run(run func(master *domain.MasterConfig, teams map[string]*domain.Team)) *MockOrgChart_RebuildFromConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.MasterConfig), args[1].(map[string]*domain.Team))
	})
	return _c
}

func (_c *MockOrgChart_RebuildFromConfig_Call) Return(_a0 error) *MockOrgChart_RebuildFromConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrgChart_RebuildFromConfig_Call) RunAndReturn(run func(*domain.MasterConfig, map[string]*domain.Team) error) *MockOrgChart_RebuildFromConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrgChart creates a new instance of MockOrgChart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrgChart(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrgChart {
	mock := &MockOrgChart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
