// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockHeartbeatMonitor

import (
	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockHeartbeatMonitor is an autogenerated mock type for the HeartbeatMonitor type
type MockHeartbeatMonitor struct {
	mock.Mock
}

type MockHeartbeatMonitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeartbeatMonitor) EXPECT() *MockHeartbeatMonitor_Expecter {
	return &MockHeartbeatMonitor_Expecter{mock: &_m.Mock}
}

// GetAllStatuses provides a mock function with no fields
func (_m *MockHeartbeatMonitor) GetAllStatuses() map[string]*domain.HeartbeatStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStatuses")
	}

	var r0 map[string]*domain.HeartbeatStatus
	if rf, ok := ret.Get(0).(func() map[string]*domain.HeartbeatStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.HeartbeatStatus)
		}
	}

	return r0
}

// MockHeartbeatMonitor_GetAllStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStatuses'
type MockHeartbeatMonitor_GetAllStatuses_Call struct {
	*mock.Call
}

// GetAllStatuses is a helper method to define mock.On call
func (_e *MockHeartbeatMonitor_Expecter) GetAllStatuses() *MockHeartbeatMonitor_GetAllStatuses_Call {
	return &MockHeartbeatMonitor_GetAllStatuses_Call{Call: _e.mock.On("GetAllStatuses")}
}

func (_c *MockHeartbeatMonitor_GetAllStatuses_Call) Run(run func()) *MockHeartbeatMonitor_GetAllStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeartbeatMonitor_GetAllStatuses_Call) Return(_a0 map[string]*domain.HeartbeatStatus) *MockHeartbeatMonitor_GetAllStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeartbeatMonitor_GetAllStatuses_Call) RunAndReturn(run func() map[string]*domain.HeartbeatStatus) *MockHeartbeatMonitor_GetAllStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: teamID
func (_m *MockHeartbeatMonitor) GetStatus(teamID string) (*domain.HeartbeatStatus, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *domain.HeartbeatStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.HeartbeatStatus, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.HeartbeatStatus); ok {
		r0 = rf(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HeartbeatStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeartbeatMonitor_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockHeartbeatMonitor_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - teamID string
func (_e *MockHeartbeatMonitor_Expecter) GetStatus(teamID interface{}) *MockHeartbeatMonitor_GetStatus_Call {
	return &MockHeartbeatMonitor_GetStatus_Call{Call: _e.mock.On("GetStatus", teamID)}
}

func (_c *MockHeartbeatMonitor_GetStatus_Call) Run(run func(teamID string)) *MockHeartbeatMonitor_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHeartbeatMonitor_GetStatus_Call) Return(_a0 *domain.HeartbeatStatus, _a1 error) *MockHeartbeatMonitor_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeartbeatMonitor_GetStatus_Call) RunAndReturn(run func(string) (*domain.HeartbeatStatus, error)) *MockHeartbeatMonitor_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessHeartbeat provides a mock function with given fields: teamID, agents
func (_m *MockHeartbeatMonitor) ProcessHeartbeat(teamID string, agents []domain.AgentHeartbeatStatus) {
	_m.Called(teamID, agents)
}

// MockHeartbeatMonitor_ProcessHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessHeartbeat'
type MockHeartbeatMonitor_ProcessHeartbeat_Call struct {
	*mock.Call
}

// ProcessHeartbeat is a helper method to define mock.On call
//   - teamID string
//   - agents []domain.AgentHeartbeatStatus
func (_e *MockHeartbeatMonitor_Expecter) ProcessHeartbeat(teamID interface{}, agents interface{}) *MockHeartbeatMonitor_ProcessHeartbeat_Call {
	return &MockHeartbeatMonitor_ProcessHeartbeat_Call{Call: _e.mock.On("ProcessHeartbeat", teamID, agents)}
}

func (_c *MockHeartbeatMonitor_ProcessHeartbeat_Call) Run(run func(teamID string, agents []domain.AgentHeartbeatStatus)) *MockHeartbeatMonitor_ProcessHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]domain.AgentHeartbeatStatus))
	})
	return _c
}

func (_c *MockHeartbeatMonitor_ProcessHeartbeat_Call) Return() *MockHeartbeatMonitor_ProcessHeartbeat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHeartbeatMonitor_ProcessHeartbeat_Call) RunAndReturn(run func(string, []domain.AgentHeartbeatStatus)) *MockHeartbeatMonitor_ProcessHeartbeat_Call {
	_c.Run(run)
	return _c
}

// SetOnUnhealthy provides a mock function with given fields: callback
func (_m *MockHeartbeatMonitor) SetOnUnhealthy(callback func(string)) {
	_m.Called(callback)
}

// MockHeartbeatMonitor_SetOnUnhealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnUnhealthy'
type MockHeartbeatMonitor_SetOnUnhealthy_Call struct {
	*mock.Call
}

// SetOnUnhealthy is a helper method to define mock.On call
//   - callback func(string)
func (_e *MockHeartbeatMonitor_Expecter) SetOnUnhealthy(callback interface{}) *MockHeartbeatMonitor_SetOnUnhealthy_Call {
	return &MockHeartbeatMonitor_SetOnUnhealthy_Call{Call: _e.mock.On("SetOnUnhealthy", callback)}
}

func (_c *MockHeartbeatMonitor_SetOnUnhealthy_Call) Run(run func(callback func(string))) *MockHeartbeatMonitor_SetOnUnhealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string)))
	})
	return _c
}

func (_c *MockHeartbeatMonitor_SetOnUnhealthy_Call) Return() *MockHeartbeatMonitor_SetOnUnhealthy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHeartbeatMonitor_SetOnUnhealthy_Call) RunAndReturn(run func(func(string))) *MockHeartbeatMonitor_SetOnUnhealthy_Call {
	_c.Run(run)
	return _c
}

// StartMonitoring provides a mock function with no fields
func (_m *MockHeartbeatMonitor) StartMonitoring() {
	_m.Called()
}

// MockHeartbeatMonitor_StartMonitoring_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartMonitoring'
type MockHeartbeatMonitor_StartMonitoring_Call struct {
	*mock.Call
}

// StartMonitoring is a helper method to define mock.On call
func (_e *MockHeartbeatMonitor_Expecter) StartMonitoring() *MockHeartbeatMonitor_StartMonitoring_Call {
	return &MockHeartbeatMonitor_StartMonitoring_Call{Call: _e.mock.On("StartMonitoring")}
}

func (_c *MockHeartbeatMonitor_StartMonitoring_Call) Run(run func()) *MockHeartbeatMonitor_StartMonitoring_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeartbeatMonitor_StartMonitoring_Call) Return() *MockHeartbeatMonitor_StartMonitoring_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHeartbeatMonitor_StartMonitoring_Call) RunAndReturn(run func()) *MockHeartbeatMonitor_StartMonitoring_Call {
	_c.Run(run)
	return _c
}

// StopMonitoring provides a mock function with no fields
func (_m *MockHeartbeatMonitor) StopMonitoring() {
	_m.Called()
}

// MockHeartbeatMonitor_StopMonitoring_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopMonitoring'
type MockHeartbeatMonitor_StopMonitoring_Call struct {
	*mock.Call
}

// StopMonitoring is a helper method to define mock.On call
func (_e *MockHeartbeatMonitor_Expecter) StopMonitoring() *MockHeartbeatMonitor_StopMonitoring_Call {
	return &MockHeartbeatMonitor_StopMonitoring_Call{Call: _e.mock.On("StopMonitoring")}
}

func (_c *MockHeartbeatMonitor_StopMonitoring_Call) Run(run func()) *MockHeartbeatMonitor_StopMonitoring_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeartbeatMonitor_StopMonitoring_Call) Return() *MockHeartbeatMonitor_StopMonitoring_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHeartbeatMonitor_StopMonitoring_Call) RunAndReturn(run func()) *MockHeartbeatMonitor_StopMonitoring_Call {
	_c.Run(run)
	return _c
}

// NewMockHeartbeatMonitor creates a new instance of MockHeartbeatMonitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeartbeatMonitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeartbeatMonitor {
	mock := &MockHeartbeatMonitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
