// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockHealthManager

import (
	context "context"

	domain "github.com/Z-M-Huang/openhive/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockHealthManager is an autogenerated mock type for the HealthManager type
type MockHealthManager struct {
	mock.Mock
}

type MockHealthManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthManager) EXPECT() *MockHealthManager_Expecter {
	return &MockHealthManager_Expecter{mock: &_m.Mock}
}

// GetAllStatuses provides a mock function with no fields
func (_m *MockHealthManager) GetAllStatuses() map[string]*domain.HeartbeatStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStatuses")
	}

	var r0 map[string]*domain.HeartbeatStatus
	if rf, ok := ret.Get(0).(func() map[string]*domain.HeartbeatStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.HeartbeatStatus)
		}
	}

	return r0
}

// MockHealthManager_GetAllStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStatuses'
type MockHealthManager_GetAllStatuses_Call struct {
	*mock.Call
}

// GetAllStatuses is a helper method to define mock.On call
func (_e *MockHealthManager_Expecter) GetAllStatuses() *MockHealthManager_GetAllStatuses_Call {
	return &MockHealthManager_GetAllStatuses_Call{Call: _e.mock.On("GetAllStatuses")}
}

func (_c *MockHealthManager_GetAllStatuses_Call) Run(run func()) *MockHealthManager_GetAllStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthManager_GetAllStatuses_Call) Return(_a0 map[string]*domain.HeartbeatStatus) *MockHealthManager_GetAllStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthManager_GetAllStatuses_Call) RunAndReturn(run func() map[string]*domain.HeartbeatStatus) *MockHealthManager_GetAllStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealthStatus provides a mock function with given fields: teamSlug
func (_m *MockHealthManager) GetHealthStatus(teamSlug string) (*domain.HeartbeatStatus, error) {
	ret := _m.Called(teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthStatus")
	}

	var r0 *domain.HeartbeatStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.HeartbeatStatus, error)); ok {
		return rf(teamSlug)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.HeartbeatStatus); ok {
		r0 = rf(teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HeartbeatStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHealthManager_GetHealthStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthStatus'
type MockHealthManager_GetHealthStatus_Call struct {
	*mock.Call
}

// GetHealthStatus is a helper method to define mock.On call
//   - teamSlug string
func (_e *MockHealthManager_Expecter) GetHealthStatus(teamSlug interface{}) *MockHealthManager_GetHealthStatus_Call {
	return &MockHealthManager_GetHealthStatus_Call{Call: _e.mock.On("GetHealthStatus", teamSlug)}
}

func (_c *MockHealthManager_GetHealthStatus_Call) Run(run func(teamSlug string)) *MockHealthManager_GetHealthStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthManager_GetHealthStatus_Call) Return(_a0 *domain.HeartbeatStatus, _a1 error) *MockHealthManager_GetHealthStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHealthManager_GetHealthStatus_Call) RunAndReturn(run func(string) (*domain.HeartbeatStatus, error)) *MockHealthManager_GetHealthStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUnhealthy provides a mock function with given fields: ctx, teamID
func (_m *MockHealthManager) HandleUnhealthy(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for HandleUnhealthy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthManager_HandleUnhealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUnhealthy'
type MockHealthManager_HandleUnhealthy_Call struct {
	*mock.Call
}

// HandleUnhealthy is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockHealthManager_Expecter) HandleUnhealthy(ctx interface{}, teamID interface{}) *MockHealthManager_HandleUnhealthy_Call {
	return &MockHealthManager_HandleUnhealthy_Call{Call: _e.mock.On("HandleUnhealthy", ctx, teamID)}
}

func (_c *MockHealthManager_HandleUnhealthy_Call) Run(run func(ctx context.Context, teamID string)) *MockHealthManager_HandleUnhealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHealthManager_HandleUnhealthy_Call) Return(_a0 error) *MockHealthManager_HandleUnhealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthManager_HandleUnhealthy_Call) RunAndReturn(run func(context.Context, string) error) *MockHealthManager_HandleUnhealthy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthManager creates a new instance of MockHealthManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthManager {
	mock := &MockHealthManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
